package cn.valorin.dueltime.yaml.message;

public enum Msg {
    LANGUAGE_NAME("LanguageName", "&c简体中文(系统内置)"),
    STRING_NONE("String.none", "无"),
    STRING_TRUE("String.true", "是"),
    STRING_FALSE("String.false", "否"),
    STRING_LIST("String.list", "{line}行列表：{brief_content}",
            "line", "brief_content"),
    STRING_WIN("String.win", "&a胜利"),
    STRING_LOSE("String.lose", "&7失败"),
    STRING_DRAW("String.draw", "&6平局"),
    STRING_GAMES("String.games", "场"),
    STRING_SECOND("String.seconds", "秒"),
    STRING_NO_RANK("String.no-rank", "&7无排名"),
    STRING_COMMAND_EXECUTOR_PLAYER("String.command-executor.player", "玩家"),
    STRING_COMMAND_EXECUTOR_OP("String.command-executor.op", "管理员"),
    STRING_COMMAND_EXECUTOR_CONSOLE("String.command-executor.console", "后台"),
    EXCEPTION_ARENA_INITIALIZE_FAIL_INVALID_ARENA_TYPE("Exception.arena.initialize-fail-invalid-arena-type", "竞技场 {arena_name}(ID:{arena_id}) 初始化失败，不存在ID为 '{arena_id}' 的竞技场类型，请检查是否缺少相关附属插件",
            "arena_id", "arena_name", "type_id"),
    LEVEL_LEVEL_UP_MESSAGE("Level.level-up-message", "&a恭喜你的DT等级升到了 &b{level} &a级",
            "level"),
    LEVEL_TIER_UP_MESSAGE("Level.tier-up-message", "&b恭喜你的DT段位升到了 &f{tier}",
            "tier"),
    LEVEL_TIER_UP_BROADCAST("Level.tier-up-broadcast", "&a[恭喜] &b玩家 &3{player} &b的段位升到了 &f{tier}",
            "player", "tier"),
    LEVEL_TIER_DOWN_MESSAGE("Level.tier-down-message", "&c你的DT段位掉到了 &f{tier}",
            "tier"),
    ARENA_WAIT_START("Arena.wait.start", "&7已加入竞技场 &b{arena}&7 的等待队列...",
            "arena"),
    ARENA_WAIT_SWITCH("Arena.wait.switch", "&7已切换至竞技场 &b{arena}&7 的等待队列...",
            "arena"),
    ARENA_WAIT_STOP("Arena.wait.stop", "&7取消等待竞技场：&b{arena}",
            "arena"),
    ARENA_PROTECTION_WALK_IN_WHILE_AVAILABLE("Arena.protection.walk-in-while-available", "&c&l[!]&c无赛事时，你不能进入竞技场 &e{name}&c 的场地"
            , "name"),
    ARENA_PROTECTION_WALK_IN_WHILE_IN_PROGRESS("Arena.protection.walk-in-while-in-progress", "&c&l[!]&c竞技场 &e{name}&c 正在比赛，请不要进入"
            , "name"),
    ARENA_PROTECTION_TELEPORT_TO_WHILE_AVAILABLE("Arena.protection.teleport-to-while-available", "&c&l[!]&c无赛事时，你不能传送到竞技场 &e{name}&c 的场地"
            , "name"),
    ARENA_PROTECTION_TELEPORT_TO_WHILE_IN_PROGRESS("Arena.protection.teleport-to-while-in-progress", "&c&l[!]&c竞技场 &e{name}&c 正在比赛，请不要传送过去"
            , "name"),
    ARENA_PROTECTION_ATTACK_GAMER("Arena.protection.attack-gamer", "&c&l[!]&c请不要干扰竞技场 &e{name}&c 上的参与玩家"
            , "name"),
    ARENA_PROTECTION_BREAK("Arena.protection.break", "&c&l[!]&c你不能破坏竞技场 &e{name}&c 内的方块"
            , "name"),
    ARENA_PROTECTION_PLACE("Arena.protection.place", "&c&l[!]&c你不能在竞技场 &e{name}&c 内放置方块"
            , "name"),
    ARENA_PROTECTION_PLACE_OVER("Arena.protection.place-over", "&c&l[!]&c你不能在竞技场 &e{name}&c 上空放置方块"
            , "name"),
    ARENA_PROTECTION_INTERACT("Arena.protection.interact", "&c&l[!]&c你不能与竞技场 &e{name}&c 内的方块交互"
            , "name"),
    ARENA_PROTECTION_POUR_LIQUID("Arena.protection.pour-liquid", "&c&l[!]&c你不能在竞技场 &e{name}&c 内倾倒液体"
            , "name"),
    ARENA_PROTECTION_GET_LIQUID("Arena.protection.get-liquid", "&c&l[!]&c你不能捞取竞技场 &e{name}&c 内的液体"
            , "name"),
    ARENA_TYPE_CLASSIC_NAME("Arena.type.classic.name", "经典"),
    ARENA_TYPE_CLASSIC_START_TITLE("Arena.type.classic.start.title", "&a&l比赛开始"),
    ARENA_TYPE_CLASSIC_START_SUBTITLE("Arena.type.classic.start.subtitle", "&f亮剑吧！"),
    ARENA_TYPE_CLASSIC_END_RESULT_STOPPED("Arena.type.classic.end.result-stopped", "&c&l[!]&c本场比赛被系统或管理员强制结束！将不会产生任何记录"),
    ARENA_TYPE_CLASSIC_END_RESULT_STOPPED_WITH_REASON("Arena.type.classic.end.result-stopped-with-reason", "&c&l[!]&c本场比赛被系统或管理员强制结束！将不会产生任何记录。强制结束原因：&f{reason}",
            "reason"),
    ARENA_TYPE_CLASSIC_END_RESULT_WIN("Arena.type.classic.end.result-win", "&2&l[!]&a你取得了本场经典模式下比赛的胜利"),
    ARENA_TYPE_CLASSIC_END_RESULT_LOSE("Arena.type.classic.end.result-lose", "&6&l[!]&c你在本场经典模式下的比赛中落败"),
    ARENA_TYPE_CLASSIC_END_RESULT_DRAW("Arena.type.classic.end.result-draw", "&b&l[!]&3本场经典模式下的比赛以平局结束"),
    ARENA_TYPE_CLASSIC_END_NOTIFY_INFO("Arena.type.classic.end.notify-info", new String[]{
            "&7&m───&f&l&m────────────────────────&7&m───",
            "    &b场地: &f{arena}",
            "    &b对手: &f{player}&7(&f{level_display_name}&7)",
            "    &b历时: &3{time}秒",
            "    &b经验: &f{exp_change}",
            "    &b更多数据：&7[clickable]more_data::&7(鼠标悬停此处查看)::&b总计伤害:&3{total_damage}||&b最大伤害:&3{max_damage}||&b平均伤害:&3{average_damage}[clickable]",
            "&7&m───&f&l&m────────────────────────&7&m───",
    },
            new String[][]{{"more_data", "", "", ""}},
            "arena", "player", "level_display_name", "time", "exp_change", "total_damage", "max_damage", "average_damage"),
    ARENA_TYPE_CLASSIC_EARN_POINT("Arena.earn-point", "&a恭喜你因赢得比赛获得了 &d{point} &a点积分，当前积分：&a{point_now}"
            , "point", "point_now"),
    ARENA_TYPE_CLASSIC_END_BROADCAST("Arena.type.classic.end.broadcast", "&3[战报] &b玩家 &d{winner} &b在经典模式竞技场 &e{arena}&b 上以 &a{time} &b秒的时间击败了对手 &e{loser} &b！",
            "arena", "winner", "loser", "time"),
    ARENA_TYPE_CLASSIC_END_BROADCAST_DRAW("Arena.type.classic.end.broadcast-draw", "&3[战报] 玩家 &d{player1} &b和 &d{player2} &b在经典模式竞技场 &e{arena}&b 上打成平手！历时 &a{time} &b秒",
            "arena", "player1", "player2", "time"),
    ARENA_TYPE_CLASSIC_DAMAGE_DURING_COUNTDOWN("Arena.type.classic.damage-during-countdown", "&7比赛还未还没正式开始，不可发起攻击"),
    ARENA_TYPE_CLASSIC_USE_COMMAND_IN_GAME("Arena.type.classic.use-command-in-game", "&c比赛过程中禁止使用这个指令"),
    ARENA_TYPE_CLASSIC_QUIT_INFORM_OPPONENT("Arena.type.classic.quit-inform-opponent", "&d你的对手主动退出了比赛！"),
    ARENA_TYPE_CLASSIC_LEAVE_SERVER_INFORM_OPPONENT("Arena.type.classic.leave-server-inform-opponent", "&d你的对手离开了服务器！"),
    ARENA_TYPE_CLASSIC_WIN_TITLE("Arena.type.classic.win-title", "&a&l赢"),
    ARENA_TYPE_CLASSIC_WIN_SUBTITLE("Arena.type.classic.win-subtitle", "&f恭喜你赢得了这场比赛！"),
    ARENA_TYPE_CLASSIC_DELAYED_BACK_GAMER_TITLE("Arena.type.classic.delayed-back.gamer-title", "&b&l{countdown}",
            "countdown"),
    ARENA_TYPE_CLASSIC_DELAYED_BACK_GAMER_SUBTITLE("Arena.type.classic.delayed-back.gamer-subtitle", "&7即将传送离开竞技场..."),
    ARENA_TYPE_CLASSIC_DELAYED_BACK_SPECTATOR_TITLE("Arena.type.classic.delayed-back.spectator-title", "&b&l{countdown}",
            "countdown"),
    ARENA_TYPE_CLASSIC_DELAYED_BACK_SPECTATOR_SUBTITLE("Arena.type.classic.delayed-back.spectator-subtitle", "&7即将传送离开观众席..."),
    ARENA_TYPE_CLASSIC_FUNCTION_TIME_LIMIT_NAME("Arena.type.classic.function.time-limit.name", "比赛限时"),
    ARENA_TYPE_CLASSIC_FUNCTION_TIME_LIMIT_DESCRIPTION("Arena.type.classic.function.time-limit.description", "为比赛设置限定时间(单位为秒)，若超出限时则根据预设方案判定输赢或平局，需要传入整数型数据"),
    ARENA_TYPE_CLASSIC_FUNCTION_TIME_LIMIT_BOSSBAR_TITLE("Arena.type.classic.function.time-limit.bossbar-title", "&f比赛剩余 &3{time} &f秒",
            "time"),
    ARENA_TYPE_CLASSIC_FUNCTION_COUNTDOWN_NAME("Arena.type.classic.function.countdown.name", "开始前倒计时"),
    ARENA_TYPE_CLASSIC_FUNCTION_COUNTDOWN_DESCRIPTION("Arena.type.classic.function.countdown.description", "为比赛设置开始前倒计时(单位为秒)，需要传入一个整数型数据表示秒数、传入一个布尔值表示是否允许倒计时期间玩家移动"),
    ARENA_TYPE_CLASSIC_FUNCTION_COUNTDOWN_GAME_TITLE("Arena.type.classic.function.time-limit.game-title", "&b&l{time}",
            "time"),
    ARENA_TYPE_CLASSIC_FUNCTION_COUNTDOWN_GAME_SUBTITLE("Arena.type.classic.function.time-limit.game-subtitle", "&f比赛即将开始...",
            "time"),
    ARENA_TYPE_CLASSIC_FUNCTION_INVENTORY_CHECK_KEYWORD_NAME("Arena.type.classic.function.check-inventory-keyword.name", "入场前背包检查(依关键词)"),
    ARENA_TYPE_CLASSIC_FUNCTION_INVENTORY_CHECK_KEYWORD_DESCRIPTION("Arena.type.classic.function.inventory-check-keyword.description", "禁用某些特殊的物品入场，检测背包中是否装有名称或lore中含有某些关键词的物品，如果有则制止开赛"),
    ARENA_TYPE_CLASSIC_FUNCTION_INVENTORY_CHECK_KEYWORD_DETECTED_TIP("Arena.type.classic.function.inventory-check-keyword.detected-tip", "&c&l[!] &c在你的背包中检测到竞技场 &e{arena_name}&c 所禁用的特殊物品： [clickable]item::&f[{item_name}]&7(点击查看详情)::{item_lore}[clickable]",
            new String[][]{{"item", "/dueltime click item", "", ""}},
            "arena_name", "item_name", "item_lore"),
    ARENA_TYPE_CLASSIC_FUNCTION_INVENTORY_CHECK_KEYWORD_DETECTED("Arena.type.classic.function.inventory-check-keyword.detected", "&c玩家 &e{player}&c 背包里携带有竞技场 &e{arena_name}&c 所禁用的特殊物品，已通知该玩家相关细节，请再次确保双方都没有携带其他禁用的特殊物品后再重新发起比赛",
            "player", "arena_name"),
    ARENA_TYPE_CLASSIC_FUNCTION_INVENTORY_CHECK_TYPE_NAME("Arena.type.classic.function.inventory-check-type.name", "入场前背包检查(依物品种类)"),
    ARENA_TYPE_CLASSIC_FUNCTION_INVENTORY_CHECK_TYPE_DESCRIPTION("Arena.type.classic.function.inventory-check-type.description", "为比赛设置背包携带物品限制，检测背包中是否装有某个特定种类的物品，如果有则制止开赛"),
    ARENA_TYPE_CLASSIC_FUNCTION_INVENTORY_CHECK_TYPE_DETECTED_TIP("Arena.type.classic.function.inventory-check-type.detected-tip", "&c&l[!] &c在你的背包中检测到竞技场 &e{arena_name}&c 所禁用的特定种类物品： [clickable]item::&f[{item_name}]&7(点击查看详情)::{item_lore}[clickable]",
            new String[][]{{"item", "/dueltime click item", "", ""}},
            "arena_name", "item_name", "item_lore"),
    ARENA_TYPE_CLASSIC_FUNCTION_INVENTORY_CHECK_TYPE_DETECTED("Arena.type.classic.function.inventory-check-type.detected", "&c玩家 &e{player}&c 背包里携带有竞技场 &e{arena_name}&c 所禁用的特定种类物品，已通知该玩家相关细节，请再次确保双方都没有携带其他禁用种类的物品后再重新发起比赛",
            "player", "arena_name"),

    ARENA_TYPE_CLASSIC_FUNCTION_PRE_GAME_COMMAND_NAME("Arena.type.classic.function.pre-game-command.name", "赛前执行指令组"),
    ARENA_TYPE_CLASSIC_FUNCTION_PRE_GAME_COMMAND_DESCRIPTION("Arena.type.classic.function.pre-game-command.description", "为比赛设置玩家赛前刚入场时执行的指令组，支持分别以不同的身份执行"),
    ARENA_TYPE_CLASSIC_FUNCTION_SPECTATE_NAME("Arena.type.classic.function.spectate.name", "观战"),
    ARENA_TYPE_CLASSIC_FUNCTION_SPECTATE_DESCRIPTION("Arena.type.classic.function.spectate.description", "为比赛设置观战区域，使得玩家可与通过/dueltime spectate指令来观看某个经典模式竞技场的比赛"),
    ARENA_TYPE_CLASSIC_FUNCTION_BAN_ENTITY_SPAWN_NAME("Arena.type.classic.function.ban-entity-spawn.name", "禁止实体生成(包括自然的与人为的)"),
    ARENA_TYPE_CLASSIC_FUNCTION_BAN_ENTITY_SPAWN_DESCRIPTION("Arena.type.classic.function.ban-entity-spawn.description", "禁止实体刷出(包括自然的与人为的)，可以设置白名单"),
    ARENA_TYPE_CLASSIC_FUNCTION_SPECTATE_GAMER_HEALTH_BOSSBAR("Arena.type.classic.function.spectate.gamer-health-bossbar", "&f选手 &b{player}&f 的实时血量：&a{health}&2/{max_health}",
            "player", "health", "max_health"),
    ARENA_TYPE_CLASSIC_FUNCTION_SPECTATE_FAIL_UNAVAILABLE("Arena.type.classic.function.spectate.fail-unavailable", "&c管理员尚未给竞技场 &e{arena} &c开启观战功能",
            "arena"),
    ARENA_TYPE_CLASSIC_FUNCTION_SPECTATE_SUCCESSFULLY("Arena.type.classic.function.spectate.successfully", "&a已将你带到竞技场 &b{arena} &a的观战区域！",
            "arena"),
    ARENA_TYPE_CLASSIC_FUNCTION_STOP_SPECTATE_SUCCESSFULLY("Arena.type.classic.function.spectate.stop-successfully", "&a你结束了对竞技场 &b{arena} &a的观看",
            "arena"),
    ARENA_TYPE_CLASSIC_FUNCTION_SPECTATE_OVER("Arena.type.classic.function.spectate.over", new String[]{
            "&a你观看的比赛结束！详情如下：",
            "&7&m───&f&l&m────────────────────────&7&m───",
            "    &b场地: &f{arena}",
            "    &b选手: &3{gamers}",
            "    &b获胜: &d{winner}",
            "    &b历时: &3{time}秒",
            "&7&m───&f&l&m────────────────────────&7&m───",
    },
            "arena", "gamers", "winner", "time"),
    ARENA_TYPE_CLASSIC_FUNCTION_SPECTATE_OVER_IN_A_DRAW("Arena.type.classic.function.spectate.over-in-a-draw", new String[]{
            "&a你观看的比赛以平局结束，详情如下：",
            "&7&m───&f&l&m────────────────────────&7&m───",
            "    &b场地: &f{arena}",
            "    &b选手: &3{gamers}",
            "    &b历时: &3{time}秒",
            "&7&m───&f&l&m────────────────────────&7&m───",
    },
            "arena", "gamers", "time"),
    ARENA_TYPE_CLASSIC_FUNCTION_SPECTATE_OVER_BY_STOP("Arena.type.classic.function.spectate.over-by-stop", "&c竞技场 &e{arena}&c 上的比赛被管理员强制结束！",
            "arena"),
    ARENA_TYPE_CLASSIC_FUNCTION_SPECTATE_SPECTATOR_MOVE_OUT_ZONE("Arena.type.classic.function.spectate.spectator-move-out-zone", "&c请不要离开观赛区域，如果要结束观赛，请再次输入观赛指令"),
    RECORD_TYPE_CLASSIC_TITLE("Record.type.classic.title", "&f经典模式比赛记录"),
    RECORD_TYPE_CLASSIC_CONTENT_ARENA_NAME("Record.type.classic.content.arena-name", "&b场地: &f{arena_name}",
            "arena_name"),
    RECORD_TYPE_CLASSIC_CONTENT_RESULT("Record.type.classic.content.result", "&b结果: &f{result}",
            "result"),
    RECORD_TYPE_CLASSIC_CONTENT_OPPONENT("Record.type.classic.content.opponent", "&b对手: &e{opponent}",
            "opponent"),
    RECORD_TYPE_CLASSIC_CONTENT_TIME("Record.type.classic.content.time", "&b用时: &e{time}秒",
            "time"),
    RECORD_TYPE_CLASSIC_CONTENT_EXP_CHANGE("Record.type.classic.content.exp-change", "&b经验变化: &f{exp_change}",
            "exp_change"),
    RECORD_TYPE_CLASSIC_CONTENT_TOTAL_DAMAGE("Record.type.classic.content.total-damage", "&b总计伤害: &e{total_damage}点",
            "total_damage"),
    RECORD_TYPE_CLASSIC_CONTENT_MAX_DAMAGE("Record.type.classic.content.max-damage", "&b最大伤害: &e{max_damage}点",
            "max_damage"),
    RECORD_TYPE_CLASSIC_CONTENT_AVERAGE_DAMAGE("Record.type.classic.content.average-damage", "&b平均伤害: &e{average_damage}点",
            "average_damage"),
    RECORD_TYPE_CLASSIC_CONTENT_DATE("Record.type.classic.content.date", "&b比赛日期: &e{date}",
            "date"),
    ERROR_NO_PERMISSION("Error.no-permission", "&c你没有权限这么做！"),
    ERROR_NOT_PLAYER_EXECUTOR("Error.not-player-executor", "&c只有玩家能执行这个指令！"),
    ERROR_SUB_COMMAND_NOT_EXISTS("Error.sub-command-not-exists", "&c子指令 &e'{enter}' &c不存在，请检查输入",
            "enter"),
    ERROR_INCORRECT_NUMBER_FORMAT("Error.incorrect-number-format", "&e'{enter}' &c不是数字，请注意格式",
            "enter"),
    ERROR_INCORRECT_INTEGER_FORMAT("Error.incorrect-integer-format", "&e'{enter}' &c不是整数，请注意格式",
            "enter"),
    ERROR_INCORRECT_ID_FORMAT("Error.incorrect-id-format", "&e'{enter}' &c不符合ID命名规范，ID只能包含英文字母、数字和下划线",
            "enter"),
    ERROR_VALUE_IS_NOT_POSITIVE("Error.value-is-not-positive", "&c请输入一个有效的正数！你所输入的 &e'{enter}' &c不符合条件",
            "enter"),
    ERROR_VALUE_IS_NEGATIVE("Error.value-is-negative", "&c请输入一个非负数！你所输入的 &e'{enter}' &c不符合条件",
            "enter"),
    ERROR_INCORRECT_BOOLEAN("Error.incorrect-boolean-format", "&c请输入字母'T'或'F'，分别表示[是]和[否]'"),
    ERROR_PLAYER_NO_FOUND("Error.player-no-found", "&c名为 &e'{player}' &c的玩家可能不存在",
            "player"),
    ERROR_INCORRECT_STRING_INTEGER_PAIR_FORMAT("Error.incorrect-string-integer-pair-format", "&c请输入 &e文字:数字 &c来表示字符串-整数对，例如 &e'example:3'"),
    ERROR_INCORRECT_STRING_INTEGER_PAIR_FORMAT_INTEGER("Error.incorrect-string-integer-pair-format-integer", "&c分割符 &e':' &c后面应该为一个整数"),
    ERROR_INCORRECT_EXECUTOR_COMMAND_PAIR_FORMAT("Error.incorrect-executor-command-pair-format", "&c请输入 &e执行身份:指令内容 &c，例如 &e'console:fly {player}'"),
    PROGRESS_REPEATEDLY_JOIN("Progress.repeatedly-join", "&c你已经在过程 &e{progress} &c中了",
            "progress"),
    PROGRESS_JOIN_WHILE_HANDLING_OTHER("Progress.join-while-handling-other", "&c请先完成或退出过程 &e{progress}",
            "progress"),
    PROGRESS_JOIN_SUCCESSFULLY("Progress.join-successfully", "&a你已进入过程 &b{progress} &a中，请按照后续提示逐步操作。&7(在此期间你可以根据需要输入&f-r&7回退步骤，输入&f-p&7暂停过程，输入&f-c&7继续过程，输入&f-e&7退出过程)",
            "progress"),
    PROGRESS_BOSSBAR_TIP("Progress.boss-bar-tip", "&a{name}({now}/{total}): {tip}",
            "name", "now", "total", "tip"),
    PROGRESS_BOSSBAR_FREE_TIP("Progress.boss-bar-free-tip", new String[]{
            "",
            "&d{progress}&f:",
            "&b进度&f:&3{now}/{total} &f[{progress_bar_progress_20_|_a_7}&f]",
            "&b提示&f:&f{tip}",
            ""},
            "progress", "now", "total", "progress_bar_progress", "tip"),
    PROGRESS_BOSSBAR_MESSAGE_FINISH_STRING("Progress.boss-bar-message-finish-string", "&a&l大功告成"),
    PROGRESS_AUTO_UPLOAD_LOCATION_DIFFERENT_WORLD("Progress.auto-upload.location-different-world", "&c你所选的位置点必须与上一个位置位于同一个世界！"),
    PROGRESS_AUTO_UPLOAD_LOCATION_THE_SAME_BLOCK("Progress.auto-upload.location-the-same-block", "&c你所选的点不能和上一个点位于同一个方块"),
    PROGRESS_AUTO_UPLOAD_LOCATION_OVERLAY_WITH_OTHER_ARENA("Progress.auto-upload.location-overlay-with-other-arena", "&c当前选点和上一个选点所构成的三维空间与竞技场 &e{arena} &c的三维空间交叠！请换一个点",
            "arena"),
    PROGRESS_FINISH_MESSAGE("Progress.finish.message", "&f你完成了过程：§a{progress}",
            "progress"),
    PROGRESS_FINISH_TITLE("Progress.finish.title", "&b✦"),
    PROGRESS_FINISH_SUBTITLE("Progress.finish.subtitle", "&f已完成过程：§a{progress}",
            "progress"),
    PROGRESS_OPERATION_REVERSE_TITLE("Progress.operation.reverse.title", "&6↺"),
    PROGRESS_OPERATION_REVERSE_SUBTITLE("Progress.operation.reverse.subtitle", "&7步骤回退"),
    PROGRESS_OPERATION_REVERSE_THE_FIRST_STEP("Progress.operation.reverse.the-first-step", "&c已经是第一步了，无法回退"),
    PROGRESS_OPERATION_PAUSE_TITLE("Progress.operation.pause.title", "&e┃┃"),
    PROGRESS_OPERATION_PAUSE_SUBTITLE("Progress.operation.pause.subtitle", "&7暂停步骤操作"),
    PROGRESS_OPERATION_PAUSE_HAS_BEEN_PAUSED("Progress.operation.pause.has-been-paused", "&c已经处于暂停状态"),
    PROGRESS_OPERATION_CONTINUE_TITLE("Progress.operation.continue.title", "&a▶"),
    PROGRESS_OPERATION_CONTINUE_SUBTITLE("Progress.operation.continue.subtitle", "&7恢复步骤操作"),
    PROGRESS_OPERATION_CONTINUE_HAS_BEEN_PAUSED("Progress.operation.continue.has-been-paused", "&c已经处于正常操作状态"),
    PROGRESS_OPERATION_EXIT_SUCCESSFULLY("Progress.operation.exit.successfully", "&7已退出过程：§a{progress}",
            "progress"),
    PROGRESS_OPERATION_LIST_ENTER_TITLE("Progress.operation.list.enter.title", "&f[&bT&f]"),
    PROGRESS_OPERATION_LIST_ENTER_SUBTITLE("Progress.operation.list.enter.subtitle", "&7已添加一行，当前列表：&f{brief_content}",
            "brief_content"),
    PROGRESS_OPERATION_LIST_INCORRECT_DATA_TYPE("Progress.operation.list.incorrect-data-type", "&c现在上传的数据类型不是列表，不能使用这个操作符"),
    PROGRESS_OPERATION_LIST_EMPTY_DATA("Progress.operation.list.empty-data", "&c请先输入一些内容"),
    PROGRESS_TYPE_UPLOAD_DATA_FOR_ARENA_FUNCTION("Progress.type.upload-data-for-arena-function", "上传附加功能所需要数据"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_NAME("Progress.type.create-classic-arena.name", "创建经典类型竞技场"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_1_TIP("Progress.type.create-classic-arena.step.1.tip", "左键点击方块以选择A点"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_1_TITLE("Progress.type.create-classic-arena.step.1.title", "&a✔"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_1_SUBTITLE("Progress.type.create-classic-arena.step.1.subtitle", "&f成功选择A点 坐标&e{}"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_2_TIP("Progress.type.create-classic-arena.step.2.tip", "左键点击方块以选择B点"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_2_TITLE("Progress.type.create-classic-arena.step.2.title", "&a✔"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_2_SUBTITLE("Progress.type.create-classic-arena.step.2.subtitle", "&f成功选择B点 坐标&e{}"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_3_TIP("Progress.type.create-classic-arena.step.3.tip", "点击屏幕使当前位置作为玩家1的出生点"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_3_TITLE("Progress.type.create-classic-arena.step.3.title", "&a✔"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_3_SUBTITLE("Progress.type.create-classic-arena.step.3.subtitle", "&f成功选择出生点1 坐标&e{}"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_4_TIP("Progress.type.create-classic-arena.step.4.tip", "点击屏幕使当前位置作为玩家2的出生点"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_4_TITLE("Progress.type.create-classic-arena.step.4.title", "&a✔"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_4_SUBTITLE("Progress.type.create-classic-arena.step.4.subtitle", "&f成功选择出生点2 坐标&e{}"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_5_TIP("Progress.type.create-classic-arena.step.5.tip", "输入竞技场ID (只能包含英文、数字、下划线）"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_5_TITLE("Progress.type.create-classic-arena.step.5.title", "&a✔"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_5_SUBTITLE("Progress.type.create-classic-arena.step.5.subtitle", "&f成功设置ID &b{}"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_6_TIP("Progress.type.create-classic-arena.step.6.tip", "输入竞技场名称 (支持颜色符号）"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_6_TITLE("Progress.type.create-classic-arena.step.6.title", "&a✔"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_6_SUBTITLE("Progress.type.create-classic-arena.step.6.subtitle", "&f成功设置名称 &f{}"),
    PROGRESS_TYPE_SET_FUNCTION_TIME_LIMIT_NAME("Progress.type.set-function-time-limit.name", "增添附加功能：时间限制"),
    PROGRESS_TYPE_SET_FUNCTION_TIME_LIMIT_STEP_1_TIP("Progress.type.set-function.time-limit.step.1.tip", "输入时间限制，单位为秒"),
    PROGRESS_TYPE_SET_FUNCTION_TIME_LIMIT_STEP_1_TITLE("Progress.type.set-function.time-limit.step.1.title", "&a✔"),
    PROGRESS_TYPE_SET_FUNCTION_TIME_LIMIT_STEP_1_SUBTITLE("Progress.type.set-function.time-limit.step.1.subtitle", "&f成功设置时间限制 &b{}秒"),
    PROGRESS_TYPE_SET_FUNCTION_COUNTDOWN_STEP_1_TIP("Progress.type.set-function.countdown.step.1.tip", "输入倒计时秒数，单位为秒"),
    PROGRESS_TYPE_SET_FUNCTION_COUNTDOWN_STEP_1_TITLE("Progress.type.set-function.countdown.step.1.title", "&a✔"),
    PROGRESS_TYPE_SET_FUNCTION_COUNTDOWN_STEP_1_SUBTITLE("Progress.type.set-function.countdown.step.1.subtitle", "&f成功设置倒计时秒数 &b{}秒"),
    PROGRESS_TYPE_SET_FUNCTION_COUNTDOWN_STEP_2_TIP("Progress.type.set-function.countdown.step.2.tip", "输入T或F分别表示允许或不允许倒计时期间玩家可以在竞技场中移动"),
    PROGRESS_TYPE_SET_FUNCTION_COUNTDOWN_STEP_2_TITLE("Progress.type.set-function.countdown.step.2.title", "&a✔"),
    PROGRESS_TYPE_SET_FUNCTION_COUNTDOWN_STEP_2_SUBTITLE("Progress.type.set-function.countdown.step.2.subtitle", "&f成功设置倒计时期间玩家是否可以移动：{}"),
    PROGRESS_TYPE_SET_FUNCTION_INVENTORY_CHECK_KEYWORD_STEP_1_TIP("Progress.type.set-function.inventory-check-keyword.step.1.tip", "输入检测范围，name表示只检测展示名，lore表示只检测描述，all表示都检查"),
    PROGRESS_TYPE_SET_FUNCTION_INVENTORY_CHECK_KEYWORD_STEP_1_TITLE("Progress.type.set-function.inventory-check-keyword.step.1.title", "&a✔"),
    PROGRESS_TYPE_SET_FUNCTION_INVENTORY_CHECK_KEYWORD_STEP_1_SUBTITLE("Progress.type.set-function.inventory-check-keyword.step.1.subtitle", "&f成功指定检测范围 &b{}"),
    PROGRESS_TYPE_SET_FUNCTION_INVENTORY_CHECK_KEYWORD_STEP_1_INCORRECT_RANGE("Progress.type.set-function.inventory-check-keyword.step.1.incorrect-range", "&e'{enter}' &c不是一个正确的检测范围，提示：输入name表示只检测展示名，输入lore表示只检测描述，输入all表示都检查",
            "enter"),
    PROGRESS_TYPE_SET_FUNCTION_INVENTORY_CHECK_KEYWORD_STEP_2_TIP("Progress.type.set-function.inventory-check-keyword.step.2.tip", "上传关键词列表，输入内容后发送即添加一行，输入-l结束并上传整个列表"),
    PROGRESS_TYPE_SET_FUNCTION_INVENTORY_CHECK_KEYWORD_STEP_2_TITLE("Progress.type.set-function.inventory-check-keyword.step.2.title", "&a✔"),
    PROGRESS_TYPE_SET_FUNCTION_INVENTORY_CHECK_KEYWORD_STEP_2_SUBTITLE("Progress.type.set-function.inventory-check-keyword.step.2.subtitle", "&f成功上传关键词列表 &b{}"),
    PROGRESS_TYPE_SET_FUNCTION_INVENTORY_CHECK_TYPE_STEP_1_TIP("Progress.type.set-function.inventory-check-type.step.1.tip", "上传种类信息列表，输入内容后发送即添加一行，格式为Material名+冒号+子ID，输入-l结束并上传整个列表"),
    PROGRESS_TYPE_SET_FUNCTION_INVENTORY_CHECK_TYPE_STEP_1_TITLE("Progress.type.set-function.inventory-check-type.step.1.title", "&a✔"),
    PROGRESS_TYPE_SET_FUNCTION_INVENTORY_CHECK_TYPE_STEP_1_SUBTITLE("Progress.type.set-function.inventory-check-type.step.1.subtitle", "&f成功上传种类信息列表 &b{}"),
    PROGRESS_TYPE_SET_FUNCTION_PRE_GAME_COMMAND_STEP_1_TIP("Progress.type.set-function.pre-game-command.step.1.tip", "上传指令列表，输入内容后发送即添加一行，格式为执行身份+冒号+内容，输入-l结束并上传整个列表"),
    PROGRESS_TYPE_SET_FUNCTION_PRE_GAME_COMMAND_STEP_1_TITLE("Progress.type.set-function.pre-game-command.step.1.title", "&a✔"),
    PROGRESS_TYPE_SET_FUNCTION_PRE_GAME_COMMAND_STEP_1_SUBTITLE("Progress.type.set-function.pre-game-command.step.1.subtitle", "&f成功上传指令组 &b{}"),
    PROGRESS_TYPE_SET_FUNCTION_PRE_GAME_COMMAND_STEP_1_INCORRECT_EXECUTOR("Progress.type.set-function.pre-game-command.step.1.incorrect-executor", "&e'{enter}' &c不是一个正确的执行身份名，提示：player表示以玩家身份执行，op表示以管理员身份执行，console表示以后台身份执行，console_single_time则表示以后台身份执行一次，不针对任何玩家",
            "enter"),
    PROGRESS_TYPE_SET_FUNCTION_SPECTATOR_STEP_1_TIP("Progress.type.set-function.spectator.step.1.tip", "左键点击方块选择观战区域A点"),
    PROGRESS_TYPE_SET_FUNCTION_SPECTATOR_STEP_1_TITLE("Progress.type.set-function.spectator.step.1.title", "&a✔"),
    PROGRESS_TYPE_SET_FUNCTION_SPECTATOR_STEP_1_SUBTITLE("Progress.type.set-function.spectator.step.1.subtitle", "&f成功选择A点 坐标&e{}"),
    PROGRESS_TYPE_SET_FUNCTION_SPECTATOR_STEP_2_TIP("Progress.type.set-function.spectator.step.2.tip", "左键点击方块选择观战区域B点"),
    PROGRESS_TYPE_SET_FUNCTION_SPECTATOR_STEP_2_TITLE("Progress.type.set-function.spectator.step.2.title", "&a✔"),
    PROGRESS_TYPE_SET_FUNCTION_SPECTATOR_STEP_2_SUBTITLE("Progress.type.set-function.spectator.step.2.subtitle", "&f成功选择B点 坐标&e{}"),
    PROGRESS_TYPE_SET_FUNCTION_SPECTATOR_STEP_3_TIP("Progress.type.set-function.spectator.step.3.tip", "点击屏幕使当前位置作为观战玩家的传送点"),
    PROGRESS_TYPE_SET_FUNCTION_SPECTATOR_STEP_3_TITLE("Progress.type.set-function.spectator.step.3.title", "&a✔"),
    PROGRESS_TYPE_SET_FUNCTION_SPECTATOR_STEP_3_SUBTITLE("Progress.type.set-function.spectator.step.3.subtitle", "&f成功选择观战传送点 坐标&e{}"),
    PROGRESS_TYPE_SET_FUNCTION_SPECTATOR_STEP_4_TIP("Progress.type.set-function.spectator.step.4.tip", "输入T或F分别表示是否向玩家展示对战双方的实时血量情况"),
    PROGRESS_TYPE_SET_FUNCTION_SPECTATOR_STEP_4_TITLE("Progress.type.set-function.spectator.step.4.title", "&a✔"),
    PROGRESS_TYPE_SET_FUNCTION_SPECTATOR_STEP_4_SUBTITLE("Progress.type.set-function.spectator.step.4.subtitle", "&f成功设置是否向玩家展示对战双方的实时血量情况：{}"),
    PROGRESS_TYPE_SET_FUNCTION_BAN_ENTITY_SPAWN_STEP_1_TIP("Progress.type.set-function.ban-entity-spawn.step.1.tip", "上传实体白名单列表，输入实体的枚举名后发送即添加一种，输入-l结束并上传整个列表，允许只输入-l跳过设置白名单"),
    PROGRESS_TYPE_SET_FUNCTION_BAN_ENTITY_SPAWN_STEP_1_TITLE("Progress.type.set-function.ban-entity-spawn.step.1.title", "&a✔"),
    PROGRESS_TYPE_SET_FUNCTION_BAN_ENTITY_SPAWN_STEP_1_SUBTITLE("Progress.type.set-function.ban-entity-spawn.step.1.subtitle", "&f成功上传枚举列表 &b{}"),
    COMMAND_PARAMETER_PLAYER("Command.parameter.player", "玩家名"),
    COMMAND_PARAMETER_VALUE("Command.parameter.value", "值"),
    COMMAND_PARAMETER_ARENA_ID("Command.parameter.arena-id", "竞技场ID"),
    COMMAND_PARAMETER_SOURCE_ARENA_ID("Command.parameter.source-arena-id", "源竞技场ID"),
    COMMAND_PARAMETER_TARGET_ARENA_ID("Command.parameter.target-arena-id", "目标竞技场ID"),
    COMMAND_PARAMETER_ARENA_TYPE("Command.parameter.arena-type", "类型"),
    COMMAND_PARAMETER_ARENA_FUNCTION_ID("Command.parameter.arena-function", "附加功能ID"),
    COMMAND_PARAMETER_LANGUAGE_FILE_NAME("Command.parameter.language-file-name", "文件名"),
    COMMAND_PARAMETER_POINT("Command.parameter.point", "积分数"),
    COMMAND_PARAMETER_PAGE("Command.parameter.page", "页数"),
    COMMAND_PARAMETER_ROW("Command.parameter.row", "行数"),
    COMMAND_PARAMETER_COLUMN("Command.parameter.line", "列数"),
    COMMAND_PARAMETER_DESCRIPTION("Command.parameter.description", "描述语"),
    COMMAND_PARAMETER_VALUE_OR_CONTENT("Command.parameter.value-or-content", "值或内容"),
    COMMAND_PARAMETER_COMMAND_EXECUTOR("Command.parameter.command-executor", "执行身份"),
    COMMAND_PARAMETER_INDEX("Command.parameter.index", "序号"),
    COMMAND_PARAMETER_RANKING_TYPE("Command.parameter.ranking-type", "排行榜类型ID"),
    COMMAND_PARAMETER_RANKING_PAGE("Command.parameter.ranking-page", "排行榜页码"),
    COMMAND_PARAMETER_REASON("Command.parameter.reason", "原因"),
    COMMAND_CORRECT("Command.correct", "&e[纠错提示] {command} &6[clickable]command::&7(点击键入)::&f点击快速输入这条指令[clickable]",
            new String[][]{{"command", "", "{command}", ""}},
            "command"),
    COMMAND_SUGGEST("Command.suggest", "&7你想输入的是否为:&f {command} &6[clickable]command::&f(点击键入)::&f点击快速输入这条指令[clickable]",
            new String[][]{{"command", "", "{command}", ""}},
            "command"),
    COMMAND_TITLE_ADMINHELP("Command.title.adminhelp", "&d管理员帮助"),
    COMMAND_TITLE_HELP("Command.title.help", "&d玩家帮助"),
    COMMAND_TITLE_POINT("Command.title.point", "&d积分帮助"),
    COMMAND_TITLE_SHOP("Command.title.shop", "&d积分兑换商城帮助"),
    COMMAND_TITLE_LEVEL("Command.title.level", "&d等级系统帮助"),
    COMMAND_TITLE_BLACKLIST("Command.title.blacklist", "&d黑名单帮助"),
    COMMAND_TITLE_LOBBY("Command.title.lobby", "&d大厅帮助"),
    COMMAND_TITLE_ARENA("Command.title.arena", "&d竞技场帮助"),
    COMMAND_TITLE_RANK("Command.title.rank", "&d排行榜帮助"),
    COMMAND_MAIN_HELP("Command.main.help", "&f查看基础帮助"),
    COMMAND_MAIN_ADMIN_HELP("Command.main.admin-help", "&f查看管理员帮助"),
    COMMAND_SUB_ARENA_SERIES_DESCRIPTION("Command.sub.arena.series-description", "&b&l查看竞技场相关指令帮助"),
    COMMAND_SUB_SHOP_SERIES_DESCRIPTION("Command.sub.shop.series-description", "&b&l查看积分商城相关指令帮助"),
    COMMAND_SUB_POINT_SERIES_DESCRIPTION("Command.sub.point.series-description", "&b&l查看积分相关指令帮助"),
    COMMAND_SUB_LEVEL_SERIES_DESCRIPTION("Command.sub.level.series-description", "&b&l查看PVP等级相关指令帮助"),
    COMMAND_SUB_RANK_SERIES_DESCRIPTION("Command.sub.rank.series-description", "&b&l查看排行榜相关指令帮助"),
    COMMAND_SUB_LOBBY_SERIES_DESCRIPTION("Command.sub.lobby.series-description", "&b&l查看大厅相关指令帮助"),
    COMMAND_SUB_BLACKLIST_SERIES_DESCRIPTION("Command.sub.blacklist.series-description", "&b&l查看黑名单相关指令帮助"),
    COMMAND_SUB_STOP_DESCRIPTION("Command.sub.stop.description", "&b&l强制停止某个竞技场的比赛"),
    COMMAND_SUB_RELOAD_DESCRIPTION("Command.sub.reload.description", "&b&l重载配置文件和所有语言文件"),
    COMMAND_SUB_START_DESCRIPTION("Command.sub.start.description", "&b打开竞技场选择面板"),
    COMMAND_SUB_SEND_DESCRIPTION("Command.sub.send.description", "&b向某个玩家发送比赛邀请"),
    COMMAND_SUB_ACCEPT_DESCRIPTION("Command.sub.accept.description", "&b接受（来自某个玩家的）比赛邀请"),
    COMMAND_SUB_DECLINE_DESCRIPTION("Command.sub.decline.description", "&b谢绝（来自某个玩家的）比赛邀请"),
    COMMAND_SUB_JOIN_DESCRIPTION("Command.sub.wait.description", "&b加入某个竞技场或其等待队列"),
    COMMAND_SUB_SHOP_DESCRIPTION("Command.sub.shop.description", "&b打开积分兑换商城"),
    COMMAND_SUB_LOBBY_DESCRIPTION("Command.sub.lobby.description", "&b前往大厅"),
    COMMAND_SUB_SPECTATE_DESCRIPTION("Command.sub.spectate.description", "&b观看某个竞技场的比赛"),
    COMMAND_SUB_QUIT_DESCRIPTION("Command.sub.quit.description", "&b退出当前比赛(比赛时使用)"),
    COMMAND_SUB_RECORD_DESCRIPTION("Command.sub.record.description", "&b打开比赛记录面板"),
    COMMAND_SUB_LANG_DESCRIPTION("Command.sub.lang.description", "&b切换语言环境"),
    COMMAND_SUB_POINT_VIEW_SELF_DESCRIPTION("Command.sub.point.view-self-description", "&b查看自己的积分"),
    COMMAND_SUB_POINT_ADD_DESCRIPTION("Command.sub.point.add-description", "&b为某个玩家增加积分"),
    COMMAND_SUB_POINT_SET_DESCRIPTION("Command.sub.point.set-description", "&b为某个玩家设置积分"),
    COMMAND_SUB_POINT_VIEW_PLAYER_DESCRIPTION("Command.sub.point.view-player-description", "&b查看某个玩家的积分"),
    COMMAND_SUB_POINT_VIEW_SELF("Command.sub.point.view-self", "&b我的积分：&d{point}",
            "point"),
    COMMAND_SUB_POINT_ADD_SUCCESSFULLY("Command.sub.point.add-successfully", "&a成功添加为玩家 &b{player} &a添加 &6{point} &a积分",
            "player", "point"),
    COMMAND_SUB_POINT_SET_SUCCESSFULLY("Command.sub.point.set-successfully", "&a成功添加将玩家 &b{player} &a的积分设置为 &6{point}",
            "player", "point"),
    COMMAND_SUB_POINT_VIEW_PLAYER("Command.sub.point.view-player", "&a玩家 &b{player} &a的积分为 &6{point}",
            "player", "point"),
    COMMAND_SUB_LANG_LIST_HEADING("Command.sub.lang.list-heading", "&b语言文件如下："),
    COMMAND_SUB_LANG_LIST_BODY("Command.sub.lang.list-body", "&2&l{index}. &a{file}[clickable]switch::&7(点击切换)::&f点击将自己的语言环境切换为：&a{file}[clickable]",
            new String[][]{{"switch", "/dueltime lang {file}", "", ""}},
            "index", "file"),
    COMMAND_SUB_LANG_LIST_ENDING("Command.sub.lang.list-ending", "&b共计 &3&l{number} &b个文件",
            "number"),
    COMMAND_SUB_LANG_NO_FILES_INSTALLED("Command.sub.lang.no-file-installed", "&c服务器未装载任何其他语言文件"),
    COMMAND_SUB_LANG_THE_FILE_NOT_EXISTS("Command.sub.lang.the-file-not-exists", "&c不存在名为 &e'{file}' &c的语言文件",
            "file"),
    COMMAND_SUB_LANG_SWITCH_SUCCESSFULLY("Command.sub.lang.switch-successfully", "&a切换成功！当前语言环境：{language}",
            "language"),
    COMMAND_SUB_BLACKLIST_ADD_DESCRIPTION("Command.sub.blacklist.add-description", "&b将某个玩家添加到黑名单中"),
    COMMAND_SUB_BLACKLIST_REMOVE_DESCRIPTION("Command.sub.blacklist.remove-description", "&b把某个玩家从黑名单中移除"),
    COMMAND_SUB_BLACKLIST_VIEW_DESCRIPTION("Command.sub.blacklist.view-description", "&b查看黑名单列表"),
    COMMAND_SUB_BLACKLIST_ADD_SUCCESSFULLY("Command.sub.blacklist.add-successfully", "&a成功将玩家 &b{player} &a添加到黑名单中",
            "player"),
    COMMAND_SUB_BLACKLIST_REMOVE_SUCCESSFULLY("Command.sub.blacklist.remove-successfully", "&a成功将玩家 &b{player} &a从黑名单中移除",
            "player"),
    COMMAND_SUB_BLACKLIST_THE_PLAYER_HAS_BEEN_IN("Command.sub.blacklist.the-player-has-been-in", "&c玩家 &e{player} &c已经在黑名单中了",
            "player"),
    COMMAND_SUB_BLACKLIST_THE_PLAYER_NOT_FOUND("Command.sub.blacklist.the-player-not-found", "&c玩家 &e'{player}' &c本来就不在黑名单中",
            "player"),
    COMMAND_SUB_BLACKLIST_VIEW_EMPTY("Command.sub.blacklist.view-empty", "&c当前黑名单中没有任何玩家"),
    COMMAND_SUB_BLACKLIST_VIEW_HEADING("Command.sub.blacklist.view-heading", "&b黑名单如下："),
    COMMAND_SUB_BLACKLIST_VIEW_BODY("Command.sub.blacklist.view-body", "&2&l{index}. &a{player}[clickable]remove::&7(点击移除)::&f点击从黑名单中移除玩家：&a{player}[clickable]",
            new String[][]{{"remove", "/dueltime blacklist remove {player}", "", ""}},
            "index", "player"),
    COMMAND_SUB_BLACKLIST_VIEW_ENDING("Command.sub.blacklist.view-ending", "&b共计 &3&l{number} &b个玩家",
            "number"),
    COMMAND_SUB_LEVEL_VIEW_SELF_DESCRIPTION("Command.sub.level.view-self-description", "&b查看自己的等级与经验信息"),
    COMMAND_SUB_LEVEL_VIEW_PLAYER_DESCRIPTION("Command.sub.level.view-player-description", "&b查看某个玩家的等级与经验"),
    COMMAND_SUB_LEVEL_EXP_DESCRIPTION("Command.sub.level.exp-description", "&b为某个玩家增加/设置经验"),
    COMMAND_SUB_LEVEL_VIEW_SELF("Command.sub.level.view-self", new String[]{
            "&7&m───&f&l&m────────────────────────&7&m───",
            "    &a当前等级: &e{level}",
            "    &a当前段位: &f{tier_title}",
            "    &a经验总量: &3{total_exp}",
            "    &a升级所需: &3{need_exp}",
            "    &a升级进度: &f{progress_bar_level_20_■_2_7} &f({progress_value}%)",
            "&7&m───&f&l&m────────────────────────&7&m───"
    },
            "level", "tier_title", "total_exp", "need_exp", "progress_bar_level", "progress_value"),
    COMMAND_SUB_LEVEL_VIEW_PLAYER("Command.sub.level.view-player", new String[]{
            "&7&m───&f&l&m────────────────────────&7&m───",
            "    &a玩家名称: &b{player}",
            "    &a当前等级: &e{level}",
            "    &a当前段位: &f{tier_title}",
            "    &a经验总量: &3{exp}",
            "&7&m───&f&l&m────────────────────────&7&m───"
    }, "player", "level", "tier_title", "exp"),
    COMMAND_SUB_LEVEL_ADD_SUCCESSFULLY("Command.sub.level.add-successfully", "&a成功添加为玩家 &b{player} &a添加 &6{exp} &a点经验",
            "player", "exp"),
    COMMAND_SUB_LEVEL_SET_SUCCESSFULLY("Command.sub.level.set-successfully", "&a成功添加将玩家 &b{player} &a的经验设置为 &6{exp}",
            "player", "exp"),
    COMMAND_SUB_STOP_FAIL_ARENA_NOT_EXISTS("Command.sub.stop.fail-arena-not-exists", "&c竞技场 &e'{arena}'&c 不存在，无法执行停止操作。请检查输入",
            "arena"),
    COMMAND_SUB_STOP_FAIL_NO_GAME("Command.sub.stop.fail-no-game", "&c竞技场 &e{arena}&c 当前不处于比赛状态",
            "arena"),
    COMMAND_SUB_STOP_TENTATIVELY("Command.sub.stop.tentatively", "&7正在强制停止模式为 &3{arena_type} &7的竞技场 &b{arena}&a 上的比赛...",
            "arena_type", "arena_name"),
    COMMAND_SUB_RELOAD_START("Command.sub.reload.start", "&7开始重载配置文件并尝试应用..."),
    COMMAND_SUB_RELOAD_SUCCESSFULLY("Command.sub.reload.successfully", "&a重载完成！历时 &b{time} &a毫秒",
            "time"),
    ITEM_GUI_SHOP_BUTTON_PREVIOUS_PAGE_NAME("Item.gui.shop.button-previous-page", "&9上一页"),
    ITEM_GUI_SHOP_BUTTON_NEXT_PAGE_NAME("Item.gui.shop.button-next-page", "&9下一页"),
    ITEM_GUI_SHOP_REWARD_INFORMATION("Item.gui.shop.reward-information", new String[]{
            "",
            "&e&l[兑换所需] &6{point}点积分",
            "&e&l[本服已兑] &6{volume}份",
            "&e&l[奖品描述] &7{description}",
            "",
    },
            "point", "volume", "description"),
    ITEM_GUI_SHOP_REWARD_LEVEL_LIMIT_TIP_YES("Item.gui.shop.reward-level-limit-tip-yes", "&2&l[&a&l!&2&l]&7你已达到兑换此奖品所需要的等级: {level}",
            "level"),
    ITEM_GUI_SHOP_REWARD_REDEEM_TIP_YES("Item.gui.shop.reward-redeem-tip-yes", "&b点击兑换：&b&l{point_now}&3/{point_need}",
            "point_now", "point_need"),
    ITEM_GUI_SHOP_REWARD_REDEEM_TIP_NO_ENOUGH_POINT("Item.gui.shop.reward-redeem-tip-no-enough-point", "&c积分不足：&c&l{point_now}&e/{point_need}",
            "point_now", "point_need"),
    ITEM_GUI_SHOP_REWARD_REDEEM_TIP_NO_ENOUGH_LEVEL("Item.gui.shop.reward-redeem-tip-no-enough-level", "&c等级不足：&c&l{level_now}&e/{level_need}",
            "level_now", "level_need"),
    ITEM_GUI_RECORD_SHOW_TIP("Item.gui.record.show-tip", "&b[左键点击] &f向聊天框中发送本记录"),
    ITEM_GUI_RECORD_PRINT_TIP("Item.gui.record.print-tip", "&d[右键点击] &f将本记录打印到手持的纸张上&7(需要消耗{point}积分)",
            "point"),
    ITEM_GUI_START_ARENA_INFORMATION("Item.gui.start.arena-information", new String[]{
            "",
            "&f状态: &f{state}",
            "&f人数: &a{now_number}&2/{max_number}",
            "",
            "{button_message}"
    },
            "state", "now_number", "max_number", "button_message"),
    ITEM_GUI_START_ARENA_STATE_WAITING("Item.gui.start.arena-state.waiting", "&a等待中"),
    ITEM_GUI_START_ARENA_STATE_IN_PROGRESS_CLOSED("Item.gui.start.arena-state.in-progress-closed", "&c进行中&7(不可中途加入)"),
    ITEM_GUI_START_ARENA_STATE_IN_PROGRESS_OPENED("Item.gui.start.arena-state.in-progress-opened", "&b进行中&3(允许中途加入)"),
    ITEM_GUI_START_ARENA_STATE_DISABLED("Item.gui.start.arena-state.disabled", "&c停用中"),
    ITEM_GUI_START_ARENA_BUTTON_MESSAGE_WAITING_START("Item.gui.start.arena-button-message.waiting-start", "&b&l[点击等待]"),
    ITEM_GUI_START_ARENA_BUTTON_MESSAGE_WAITING_STOP("Item.gui.start.arena-button-message.waiting-stop", "&3&l[点击取消等待]"),
    ITEM_GUI_START_ARENA_BUTTON_MESSAGE_IN_PROGRESS_CLOSED("Item.gui.start.arena-button-message.in-progress-closed", "&c&l[不可加入]"),
    ITEM_GUI_START_ARENA_BUTTON_MESSAGE_IN_PROGRESS_OPENED("Item.gui.start.arena-button-message.in-progress-opened", "&a&l[点击加入]"),
    ITEM_GUI_START_ARENA_BUTTON_MESSAGE_IN_PROGRESS_OPENED_FULL("Item.gui.start.arena-button-message.in-progress-opened-full", "&c&l[人数已满]"),
    ITEM_GUI_START_ARENA_BUTTON_MESSAGE_DISABLED("Item.gui.start.arena-button-message.disabled", "&c&l[不可用]"),
    GUI_ALREADY_THE_FIRST_PAGE("GUI.already-the-first-page", "&c已经是第一页了"),
    GUI_ALREADY_THE_LAST_PAGE("GUI.already-the-last-page", "&c已经是最后一页了"),
    GUI_TYPE_SHOP_TITLE("GUI.type.shop.title", "&9积分兑换商城"),
    GUI_TYPE_SHOP_EMPTY("GUI.type.shop.empty", "&c积分兑换商城暂未设置任何奖品"),
    GUI_TYPE_SHOP_REDEEM_UNSUCCESSFULLY_INSUFFICIENT_POINTS("GUI.type.shop.redeem-unsuccessfully-insufficient-points", "&c积分不足！你需要 &e{point_need} &c才能兑换这个奖品，而你目前只有 &e{point_now}",
            "point_need", "point_now"),
    GUI_TYPE_SHOP_REDEEM_UNSUCCESSFULLY_INSUFFICIENT_LEVEL("GUI.type.shop.redeem-unsuccessfully-insufficient-level", "&c等级不足！你需要达到 &e{level_need} &c级兑换这个奖品，而你目前为 &e{level_now} &c级，请继续努力",
            "level_need", "level_now"),
    GUI_TYPE_SHOP_REDEEM_SUCCESSFULLY("GUI.type.shop.redeem-successfully", "&b兑换成功！奖品已发送到你的背包"),
    GUI_TYPE_SHOP_REDEEM_SUCCESSFULLY_BUT_DROP("GUI.type.shop.redeem-successfully-but-drop", "&3兑换成功！&b&n但由于背包空间不足，兑换到的奖品以掉落物的形式在你当前的位置出现，总共 {number} 种",
            "number"),
    GUI_TYPE_RECORD_TITLE("GUI.type.record.title", "&9{player}的比赛记录",
            "player"),
    GUI_TYPE_RECORD_EMPTY("GUI.type.record.empty", "&c暂时没有任何比赛记录"),
    GUI_TYPE_RECORD_SHOW_FREQUENTLY("GUI.type.record.show-frequently", "&c请等待 &e{time} &c秒再展示比赛记录",
            "time"),
    GUI_TYPE_RECORD_SHOW_CONTENT("GUI.type.record.show-content", "&f{player} &7: [clickable]show::&b[我的比赛记录]::{content}[clickable]&7(鼠标移动到文字上方查看)",
            new String[][]{{"show", "", "", ""}},
            "player", "content"),
    GUI_TYPE_RECORD_PRINT_INSUFFICIENT_POINT("GUI.type.record.print-insufficient-point", "&c需要 &e{point_need} &c点积分才能打印一次比赛记录，而你现在只有 &e{point_now} &c点",
            "point_need", "point_now"),
    GUI_TYPE_RECORD_PRINT_FAIL_NO_PAPER_IN_HAND("GUI.type.record.print-fail-no-paper-in-hand", "&c请先把纸张拿在手上"),
    GUI_TYPE_RECORD_PRINT_FAIL_PAPER_HAS_META("GUI.type.record.print-fail-paper-has-meta", "&c打印用的纸张应为普通的纸"),
    GUI_TYPE_RECORD_PRINT_SUCCESSFULLY("GUI.type.record.print-successfully", "&a打印成功！请查看你的纸张"),
    GUI_TYPE_START_TITLE("GUI.type.start.title", "&9竞技场列表"),
    GUI_TYPE_START_EMPTY("GUI.type.start.empty", "&c服务器未创建任何竞技场"),
    GUI_TYPE_START_USE_WHILE_IN_GAME("GUI.type.start.use-while-in-game", "&c你现在正处于竞技场 &e{arena}&c 的比赛中，无法执行此操作",
            "arena"),
    GUI_TYPE_START_WAITING_OPERATION_COOLDOWN("GUI.type.start.state.waiting-operation-cooldown", "&7请不要过于频繁地操作等待功能"),
    GUI_TYPE_START_STATE_IN_PROGRESS_CLOSED("GUI.type.start.state.in-progress-closed", "&c竞技场 &e{arena}&c 不允许中途加入",
            "arena"),
    GUI_TYPE_START_STATE_IN_PROGRESS_OPENED_FULL("GUI.type.start.state.in-progress-opened-full", "&c竞技场 &e{arena}&c 已经满人，暂不可加入",
            "arena"),
    GUI_TYPE_START_STATE_IN_PROGRESS_OPENED("GUI.type.start.state.in-progress-opened", "&a正在加入竞技场：&b{arena}",
            "arena"),
    GUI_TYPE_START_STATE_DISABLED("GUI.type.start.state.disabled", "&c竞技场 &e{arena}&c 处于停用状态！",
            "arena"),
    GUI_TYPE_ITEM_DETAIL_TITLE("GUI.type.item-display.title", "&9物品详情"),
    COMMAND_SUB_SHOP_HELP_DESCRIPTION("Command.sub.shop.help-description", "&b&l查看积分兑换商城的管理员帮助"),
    COMMAND_SUB_SHOP_ADD_DESCRIPTION("Command.sub.shop.add-description", "&b将手上的物品作为奖品添加到积分兑换商城中"),
    COMMAND_SUB_SHOP_DELETE_DESCRIPTION("Command.sub.shop.delete-description", "&b删除某个奖品"),
    COMMAND_SUB_SHOP_RESET_DESCRIPTION("Command.sub.shop.reset-description", "&b为某个奖品重设价格/描述/等级限制"),
    COMMAND_SUB_SHOP_COMMAND_ADD_DESCRIPTION("Command.shop.command.add-description", "&b为某个奖品添加一条兑换后执行的指令"),
    COMMAND_SUB_SHOP_COMMAND_REMOVE_DESCRIPTION("Command.shop.command.remove-description", "&b为某个奖品移除一条兑换后执行的指令"),
    COMMAND_SUB_SHOP_COMMAND_CLEAR_DESCRIPTION("Command.sub.shop.command.clear-description", "&b移除某个奖品的所有兑换后指令"),
    COMMAND_SUB_SHOP_COMMAND_LIST_DESCRIPTION("Command.sub.shop.command.list-description", "&b查看某个奖品的所有兑换后指令"),
    COMMAND_SUB_SHOP_ADD_SUCCESSFULLY("Command.sub.shop.add-successfully", "&a奖品添加成功！&2(位置：第{page}页，第{row}行，第{column}行)",
            "page", "row", "column"),
    COMMAND_SUB_SHOP_ADD_EMPTY_ITEMSTACK("Command.sub.shop.add-empty-itemstack", "&c请把要上架的物品拿在手上！"),
    COMMAND_SUB_SHOP_DELETE_SUCCESSFULLY("Command.sub.shop.delete-successfully", "&a奖品删除成功！&2(位置：第{page}页，第{row}行，第{column}行)",
            "page", "row", "column"),
    COMMAND_SUB_SHOP_INVALID_LOC("Command.sub.shop.invalid-loc", "&c不存在位置为&e'第{page}页，第{row}行，第{column}行'&c的奖品，请重新检查输入",
            "page", "row", "column"),
    COMMAND_SUB_SHOP_RESET_POINT_SUCCESSFULLY("Command.sub.shop.reset-point-successfully", "&a成功修改兑换积分需求为 &b{point} &a点！&2(位置：第{page}页，第{row}行，第{column}行)",
            "point", "page", "row", "column"),
    COMMAND_SUB_SHOP_RESET_DESCRIPTION_SUCCESSFULLY("Command.sub.shop.reset-description-successfully", "&a成功修改奖品的描述为&f'&7{description}&f'  &2(位置：第{page}页，第{row}行，第{column}行)",
            "description", "page", "row", "column"),
    COMMAND_SUB_SHOP_RESET_LEVEL_LIMIT_SUCCESSFULLY("Command.sub.shop.reset-level-limit-successfully", "&a成功修改兑换的等级限制为 &b{level} &a级！ &2(位置：第{page}页，第{row}行，第{column}行)",
            "level", "page", "row", "column"),
    COMMAND_SUB_SHOP_COMMAND_ADD_SUCCESSFULLY("Command.sub.shop.command-add-successfully", "&a成功添加兑换后指令 &f{command_content}&f &a执行身份为&b{command_executor} &2(位置：第{page}页，第{row}行，第{column}行)",
            "command_content", "command_executor", "page", "row", "column"),
    COMMAND_SUB_SHOP_COMMAND_ADD_TIP_COMMAND_EXECUTOR("Command.sub.shop.command-add-tip-executor",
            new String[]{
                    "&e[用法提示]",
                    "&7'{enter}' &f不是一个有效的执行身份",
                    "&f执行身份：&b'player'&f或&b'p'&f代表&b玩家；&d'player'&f或&d'p'&f代表&d玩家；&e'player'&f或&e'p'&f代表&e后台",
                    "&f示例：&e{command_entered_corrected} [clickable]type::&7(点击键入)::&f点击快速键入这条指令[clickable]"
            },
            new String[][]{{"type", "", "{command_entered_corrected}", ""}},
            "enter", "command_entered_corrected"),
    COMMAND_SUB_SHOP_COMMAND_REMOVE_SUCCESSFULLY("Command.sub.shop.command-remove-successfully", "&a成功删除兑换后指令 &f'&7/{command}&f' &2(奖品位置：第{page}页，第{row}行，第{column}行；指令序号：{index})",
            "command", "page", "row", "column", "index"),
    COMMAND_SUB_SHOP_COMMAND_INDEX_IS_NOT_FOUND("Command.sub.shop.command-index-is-not-found", "&e'{index}' &c不是一个正确的指令序号，请检查输入",
            "index"),
    COMMAND_SUB_SHOP_COMMAND_CLEAR_SUCCESSFULLY("Command.sub.shop.command-clear-successfully", "&a成功清除了 &b{number} &a条兑换后指令 &2(位置：第{page}页，第{row}行，第{column}行)",
            "number", "page", "row", "column"),
    COMMAND_SUB_SHOP_COMMAND_EMPTY("Command.sub.shop.command-empty", "&c该奖品没有设置任何兑换后执行的指令"),
    COMMAND_SUB_SHOP_COMMAND_LIST_HEADING("Command.sub.shop.command-list-heading", "&b兑换后指令列表如下： &3(位置：第{page}页，第{row}行，第{column}行)",
            "page", "row", "column"),
    COMMAND_SUB_SHOP_COMMAND_LIST_BODY("Command.sub.shop.command-list-body", "&2&l{index}. &a/{command_content} &f(执行身份:{command_executor}) [clickable]remove::&7[点击移除]::&f点击移除这条指令[clickable]",
            new String[][]{{"remove", "/dueltime shop command remove {page} {row} {column} {index}", "", ""}},
            "index", "command_content", "command_executor", "page", "row", "column"),
    COMMAND_SUB_SHOP_COMMAND_LIST_ENDING("Command.sub.shop.command-list-ending", "&b共计 &3&l{number} &b条兑换后指令",
            "number"),
    COMMAND_SUB_SEND_FAIL_SELF_IN_BLACK_LIST("Command.sub.send.fail-self-in-black-list", "&c当前你处于黑名单中，无法发起比赛邀请"),
    COMMAND_SUB_SEND_FAIL_SEND_TO_SELF("Command.sub.send.fail-send-to-self", "&c你不能向自己发送比赛邀请，请输入其他玩家名"),
    COMMAND_SUB_SEND_FAIL_NO_ARENAS("Command.sub.send.fail-no-arenas", "&c服务器没有设置任何竞技场，无法发起比赛邀请"),
    COMMAND_SUB_SEND_FAIL_OFFLINE("Command.sub.send.fail-offline", "&c无法发送比赛邀请：玩家 &e'{player}' &c不在线或不存在",
            "player"),
    COMMAND_SUB_SEND_FAIL_RECIPIENT_IN_BLACK_LIST("Command.sub.send.fail-recipient-in-black-list", "&c当前玩家 &e{player} &c处于黑名单中，无法向其发送比赛邀请",
            "player"),
    COMMAND_SUB_SEND_FAIL_INVALID_ARENA_ID("Command.sub.send.fail-invalid-arena-id", "&cID为竞技场 &e'{enter}' &c的竞技场不存在，请检查输入",
            "enter"),
    COMMAND_SUB_SEND_FAIL_ARENA_DISABLED("Command.sub.send.fail-arena-disabled", "&c竞技场 &e{arena} &c处于停用状态，请换一个指定",
            "arena"),
    COMMAND_SUB_SEND_FAIL_FREQUENTLY("Command.sub.send.fail-frequently", "&c你在 &e{second} &c秒前已经向玩家 &e{player} &c发送过比赛邀请了，请等待对方处理",
            "second", "player"),
    COMMAND_SUB_SEND_SUCCESSFULLY("Command.sub.send.successfully", "&a成功向玩家 &b{player} &a发送比赛邀请，请等待对方处理",
            "player"),
    COMMAND_SUB_SEND_RECEIVE("Command.sub.send.receive",
            new String[]{
                    "&7&m───&f&l&m────────────────────────&7&m───",
                    "",
                    " &b收到来自&e{player}&b的比赛邀请  [clickable]accept::&a&l[✔]::&a点击接受邀请[clickable] [clickable]decline::&c&l[✘]::&c点击谢绝邀请[clickable]",
                    "",
                    "&7&m───&f&l&m────────────────────────&7&m───"
            },
            new String[][]{{"accept", "/dueltime accept", "", ""}, {"decline", "/dueltime decline", "", ""}},
            "player"),
    COMMAND_SUB_SEND_RECEIVE_NOTIFY_DESIGNATED_ARENA("Command.sub.send.receive-notify-designated-arena", "&3&l[!]&f对方指定了竞技场地图&e{arena_name}&7({arena_type}&7)",
            "arena_name", "arena_type"),
    COMMAND_SUB_ACCEPT_FAIL_NONE("Command.sub.accept.fail-none", "&c你没有任何待接受的邀请"),
    COMMAND_SUB_ACCEPT_FAIL_TIME_OUT("Command.sub.accept.fail-time-out", "&c失效邀请：玩家 &e{player} &c向你发送的邀请因为长时间未被处理而失效了",
            "player"),
    COMMAND_SUB_ACCEPT_FAIL_OFFLINE("Command.sub.accept.fail-offline", "&c无效邀请：玩家 &e'{player}' &c不在线或不存在",
            "player"),
    COMMAND_SUB_ACCEPT_FAIL_HAS_NOT_SENT("Command.sub.accept.fail-has-not-sent", "&c无效邀请：玩家 &e'{player}' &c还未向你发送过邀请",
            "player"),
    COMMAND_SUB_ACCEPT_FAIL_NO_ARENAS("Command.sub.accept.fail-has-no-arenas", "&c服务器没有设置任何竞技场，无法开始比赛"),
    COMMAND_SUB_ACCEPT_FAIL_NO_AVAILABLE_ARENAS("Command.sub.accept.fail-has-no-available-arenas", "&c服务器还未设置最小开赛人数小于3的竞技场"),
    COMMAND_SUB_ACCEPT_FAIL_NO_AVAILABLE_ARENAS_TEMPORARILY("Command.sub.accept.fail-has-no-available-arenas-temporarily", "&c当前暂时没有可用的最小开赛人数小于3的竞技场"),
    COMMAND_SUB_ACCEPT_SUCCESS_RECEIVER("Command.sub.accept.success-receiver", "&a已接受玩家 &b{player} &a的邀请",
            "player"),
    COMMAND_SUB_ACCEPT_SUCCESS_SENDER("Command.sub.accept.success-sender", "&a玩家 &b{player} &a接受了你的邀请",
            "player"),
    COMMAND_SUB_ACCEPT_SUCCESS_NOTIFY_RANDOMLY_CHOSEN_ARENA("Command.sub.accept.success-notify-randomly-chosen-arena", "&b&l[!]&3由于没有指定竞技场，系统自动为你们随机选择了竞技场&f{arena_name}&7(&f{arena_type}&7)",
            "arena_name", "arena_type"),
    COMMAND_SUB_ACCEPT_CHOOSE_LIST_HEADING("Command.sub.accept.choose-list-heading", "&b当前你有多个待处理的邀请，请选择要接受的："),
    COMMAND_SUB_ACCEPT_CHOOSE_LIST_BODY("Command.sub.accept.choose-list-body", "&f&l{index}. &f{player} &7(指定竞技场: {arena}) [clickable]accept::&a&l[接受]::&a点击接受邀请[clickable]",
            new String[][]{
                    {"accept", "/dueltime accept {player}", "", ""}},
            "index", "arena", "player"),
    COMMAND_SUB_ACCEPT_CHOOSE_LIST_ENDING("Command.sub.accept.choose-list-ending", "&b共计 &3&l{number} &b条待处理邀请",
            "number"),
    COMMAND_SUB_DECLINE_FAIL_NONE("Command.sub.accept.decline-none", "&c你没有任何待拒绝的邀请"),
    COMMAND_SUB_DECLINE_FAIL_TIME_OUT("Command.sub.decline.fail-time-out", "&c失效邀请：玩家 &e{player} &c向你发送的邀请因为长时间未被处理而失效了",
            "player"),
    COMMAND_SUB_DECLINE_FAIL_OFFLINE("Command.sub.decline.fail-offline", "&c无效邀请：玩家 &e'{player}' &c不在线或不存在",
            "player"),
    COMMAND_SUB_DECLINE_FAIL_HAS_NOT_SENT("Command.sub.decline.fail-has-not-sent", "&c无效邀请：玩家 &e'{player}' &c还未向你发送过邀请",
            "player"),
    COMMAND_SUB_DECLINE_SUCCESS_RECEIVER("Command.sub.decline.success-receiver", "&a已拒绝玩家 &b{player} &a的邀请",
            "player"),
    COMMAND_SUB_DECLINE_SUCCESS_SENDER("Command.sub.decline.success-sender", "&c玩家 &6{player} &c谢绝了你的邀请",
            "player"),
    COMMAND_SUB_DECLINE_CHOOSE_LIST_HEADING("Command.sub.decline.choose-list-heading", "&b当前你有多个待处理的邀请，请选择要拒绝的："),
    COMMAND_SUB_DECLINE_CHOOSE_LIST_BODY("Command.sub.decline.choose-list-body", "&f&l{index}. &f{player} [clickable]decline::&c&l[拒绝]::&c点击拒绝邀请[clickable]",
            new String[][]{
                    {"decline", "/dueltime decline {player}", "", ""}},
            "index", "player"),
    COMMAND_SUB_DECLINE_CHOOSE_LIST_ENDING("Command.sub.decline.choose-list-ending", "&b共计 &3&l{number} &b条待处理邀请",
            "number"),

    COMMAND_SUB_START_FAIL_SELF_IN_BLACK_LIST("Command.sub.start.fail-self-in-black-list", "&c当前你处于黑名单中，无法启动开始面板"),
    COMMAND_SUB_JOIN_FAIL_ARENA_NOT_EXISTS("Command.sub.join.arena-not-exists", "&c竞技场 &e'{arena}'&c 不存在，无法加入。请检查输入",
            "arena"),
    COMMAND_SUB_JOIN_FAIL_ARENA_DISABLED("Command.sub.join.fail-arena-disabled", "&c竞技场 &e{arena}&c 处于停用状态，暂不可加入",
            "arena"),
    COMMAND_SUB_JOIN_FAIL_ARENA_IN_PROGRESS_CLOSED("Command.sub.join.arena-in-progress-closed", "&c竞技场 &e{arena}&c 不允许中途加入！",
            "arena"),
    COMMAND_SUB_JOIN_FAIL_ARENA_IN_PROGRESS_OPENED_FULL("Command.sub.join.arena-in-progress-opened-full", "&c竞技场 &e{arena}&c 人数已满，请稍后再尝试加入",
            "arena"),
    COMMAND_SUB_JOIN_GAME_TENTATIVELY("Command.sub.join.game-tentatively", "&a正在尝试加入竞技场：&b{arena}",
            "arena"),
    COMMAND_SUB_LOBBY_HELP_DESCRIPTION("Command.sub.lobby.help-description", "&b查看大厅的管理员帮助"),
    COMMAND_SUB_LOBBY_SET_DESCRIPTION("Command.sub.lobby.set-description", "&b将当前所在位置设置为大厅"),
    COMMAND_SUB_LOBBY_DELETE_DESCRIPTION("Command.sub.lobby.delete-description", "&b删除大厅"),
    COMMAND_SUB_LOBBY_NONE("Command.sub.lobby.none", "&c服务器未设置大厅传送点"),
    COMMAND_SUB_LOBBY_SET_SUCCESSFULLY("Command.sub.lobby.set-successfully", "&a成功设置大厅传送点为你当前位置"),
    COMMAND_SUB_LOBBY_UPDATE_SUCCESSFULLY("Command.sub.lobby.update-successfully", "&a大厅传送点已更新为你当前位置"),
    COMMAND_SUB_LOBBY_DELETE_FAIL_NONE("Command.sub.lobby.delete-fail-none", "&c服务器本来就没设置大厅传送点"),
    COMMAND_SUB_LOBBY_DELETE_SUCCESSFULLY("Command.sub.lobby.delete-successfully", "&a成功移除大厅传送点"),
    COMMAND_SUB_ARENA_LIST_DESCRIPTION("Command.sub.arena.list-description", "&b查看所有竞技场"),
    COMMAND_SUB_ARENA_TYPE_DESCRIPTION("Command.sub.arena.info-description", "&b查看本服已装载的全部竞技场类型"),
    COMMAND_SUB_ARENA_CREATE_DESCRIPTION("Command.sub.arena.create-description", "&b创建指定类型的竞技场"),
    COMMAND_SUB_ARENA_VIEW_DESCRIPTION("Command.sub.arena.view-description", "&b查看某个竞技场的属性信息"),
    COMMAND_SUB_ARENA_DELETE_DESCRIPTION("Command.sub.arena.delete-description", "&b删除某个竞技场"),
    COMMAND_SUB_ARENA_FUNCTION_ADD_DESCRIPTION("Command.sub.arena.function-add-description", "&b为某个竞技场增加一项附加功能"),
    COMMAND_SUB_ARENA_FUNCTION_REMOVE_DESCRIPTION("Command.sub.arena.function-remove-description", "&b为某个竞技场移除一项附加功能"),
    COMMAND_SUB_ARENA_FUNCTION_RESET_DESCRIPTION("Command.sub.arena.function-reset-description", "&b为某个竞技场的某项附加功能重设数据"),
    COMMAND_SUB_ARENA_FUNCTION_CLEAR_DESCRIPTION("Command.sub.arena.function-clear-description", "&b为某个竞技场清除所有附加功能"),
    COMMAND_SUB_ARENA_FUNCTION_LIST_DESCRIPTION("Command.sub.arena.function-list-description", "&b查看某个竞技场的所有附加功能"),
    COMMAND_SUB_ARENA_FUNCTION_TYPE_DESCRIPTION("Command.sub.arena.function-type-description", "&b查看某个竞技场类型所定义的所有附加功能"),
    COMMAND_SUB_ARENA_FUNCTION_COPY_DESCRIPTION("Command.sub.arena.function-copy-description", "&b复制某个竞技场的某个附加功能到另一个竞技场"),
    COMMAND_SUB_ARENA_LIST_EMPTY("Command.sub.arena.list-empty", "&c服务器内未设置任何竞技场！"),
    COMMAND_SUB_ARENA_LIST_HEADING("Command.sub.arena.list-heading", "&b竞技场列表如下："),
    COMMAND_SUB_ARENA_LIST_BODY("Command.sub.arena.list-body", "&f&l{index}. &f{arena_name} &3(类型:{arena_type} ID:{arena_id})",
            "index", "arena_name", "arena_type", "arena_id"),
    COMMAND_SUB_ARENA_LIST_ENDING("Command.sub.arena.list-ending", "&b共计 &3&l{number} &b个竞技场",
            "number"),
    COMMAND_SUB_ARENA_TYPE_HEADING("Command.sub.arena.type-heading", "&b竞技场类型如下："),
    COMMAND_SUB_ARENA_TYPE_BODY("Command.sub.arena.type-body", "&f&l{index}. &b{arena_type_name} &3(ID:{arena_type_id})",
            "index", "arena_type_name", "arena_type_id"),
    COMMAND_SUB_ARENA_TYPE_ENDING("Command.sub.arena.type-ending", "&b共计 &3&l{number} &b个类型",
            "number"),
    COMMAND_SUB_ARENA_CREATE_FAIL_INVALID_TYPE("Command.sub.arena.create-fail-invalid-type", "&c不存在 &e'{enter}' &c这个类型 [clickable]view::&f&n点击查看所有类型[clickable]",
            new String[][]{
                    {"view", "/dueltime arena type", "", ""}},
            "enter"),
    COMMAND_SUB_ARENA_INVALID_ID("Command.sub.arena.invalid-id", "&c不存在ID为 &e'{enter}' &c的竞技场 [clickable]view::&f&n点击查看所有竞技场对应的ID[clickable]",
            new String[][]{
                    {"view", "/dueltime arena list", "", ""}},
            "enter"),
    COMMAND_SUB_ARENA_TYPE_INVALID_ID("Command.sub.arena.type.invalid-id", "&c不存在类型ID为 &e'{enter}' &c的竞技场 [clickable]view::&f&n点击查看所有类型的竞技场对应的ID[clickable]",
            new String[][]{
                    {"view", "/dueltime arena type", "", ""}},
            "enter"),
    COMMAND_SUB_ARENA_FUNCTION_INVALID_ID("Command.sub.arena.function.invalid-id", "&6{arena_type_entered} &c类型的竞技场未定义ID为 &e'{function_entered}' &c的附加功能 [clickable]view::&f&n点击查看{arena_type_entered}类型的竞技场定义的所有功能ID[clickable]",
            new String[][]{
                    {"view", "/dueltime arena function type {arena_type_id}", "", ""}},
            "arena_type_entered", "function_entered", "arena_type_id"),
    COMMAND_SUB_ARENA_FUNCTION_TYPE_EMPTY("Command.sub.arena.function.type-empty", "&c{arena_type}类型的竞技场没有定义任何附加功能",
            "arena_type"),
    COMMAND_SUB_ARENA_FUNCTION_TYPE_HEADING("Command.sub.arena.function.type-heading", "&b{arena_type}类型的竞技场定义的附加功能如下：",
            "arena_type"),
    COMMAND_SUB_ARENA_FUNCTION_TYPE_BODY("Command.sub.arena.function.type-body", new String[]{
            "&f&l{index}. &b{arena_function_name} &3(ID:{arena_function_id})",
            "&7描述：{arena_function_description}"},
            "index", "arena_function_name", "arena_function_id", "arena_function_description"),
    COMMAND_SUB_ARENA_FUNCTION_TYPE_ENDING("Command.sub.arena.function.type-ending", "&b共计 &3&l{number} &b种附加功能",
            "number"),
    COMMAND_SUB_ARENA_FUNCTION_COPY_INVALID_SOURCE_ARENA_ID("Command.sub.arena.function.copy-invalid-source-arena-id", "&c请输入一个有效的源竞技场ID！ID为 &e'{enter}' &c的竞技场不存在 [clickable]view::&f&n点击查看所有竞技场对应的ID[clickable]",
            new String[][]{
                    {"view", "/dueltime arena list", "", ""}},
            "enter"),
    COMMAND_SUB_ARENA_FUNCTION_COPY_INVALID_TARGET_ARENA_ID("Command.sub.arena.function.copy-invalid-target-arena-id", "&c请输入一个有效的目标竞技场ID！ID为 &e'{enter}' &c的竞技场不存在 [clickable]view::&f&n点击查看所有竞技场对应的ID[clickable]",
            new String[][]{
                    {"view", "/dueltime arena list", "", ""}},
            "enter"),
    COMMAND_SUB_ARENA_FUNCTION_COPY_DIFFERENT_TYPE("Command.sub.arena.function.copy-different-type", "&c不可以对不同类型的竞技场进行该复制操作！源竞技场 &e{source_arena_name}&c为 &e{source_arena_type}&c 的，而目标竞技场 &e{target_arena_name}&c 为{target_arena_type}的！",
            "source_arena_name", "source_arena_type", "target_arena_name", "target_arena_type"),
    COMMAND_SUB_ARENA_FUNCTION_COPY_EMPTY_FUNCTION("Command.sub.arena.function.copy-empty-function", "&c源竞技场 &e{source_arena_name}&c 尚未添加附加功能：&e{function} [clickable]view::&f&n点击查看{source_arena_type}类型的竞技场定义的所有功能ID[clickable]",
            new String[][]{
                    {"view", "/dueltime arena function type {source_arena_type_id}", "", ""}},
            "source_arena_name", "function", "source_arena_type", "source_arena_type_id"),
    COMMAND_SUB_ARENA_FUNCTION_COPY_SUCCESSFULLY("Command.sub.arena.function.copy-successfully", "&a成功将竞技场 &3{source_arena}&a 的附加功能数据 &e{function} &a复制到了竞技场 &b{target_arena} &a中！",
            "source_arena", "target_arena", "function"),
    COMMAND_SUB_ARENA_FUNCTION_COPY_SUCCESSFULLY_OVERWRITE("Command.sub.arena.function.copy-successfully-overwrite", "&a成功将竞技场 &3{source_arena}&a 的附加功能数据 &e{function} &a复制，并覆盖了竞技场 &b{target_arena} &a原本相应的数据！",
            "source_arena", "target_arena", "function"),
    COMMAND_SUB_ARENA_FUNCTION_ADD_REPEATEDLY("Command.sub.arena.function.add-repeatedly", "&c竞技场 &6{arena} &c已经包含了ID为 &e'{function_entered}' &c的附加功能了，无需重复添加",
            "arena", "function_entered"),
    COMMAND_SUB_ARENA_FUNCTION_ADD_ENTER_PROGRESS("Command.sub.arena.function.add-enter-progress", "&d尝试为竞技场 &a{arena} &d增添附加功能 &b{function}&d，请按照提示完成操作",
            "arena", "function"),
    COMMAND_SUB_ARENA_FUNCTION_ADD_SUCCESSFULLY("Command.sub.arena.function.add-successfully", "&a成功为竞技场 &e{arena} &a增添附加功能 &b{function}",
            "arena", "function"),
    COMMAND_SUB_ARENA_FUNCTION_REMOVE_FAIL_NOT_EXISTS("Command.sub.arena.function.remove-fail-not-exists", "&c竞技场 &e{arena} &c本来就未增添ID为 &e'{function_id}' &c的附加功能",
            "arena", "function"),
    COMMAND_SUB_ARENA_FUNCTION_REMOVE_SUCCESSFULLY("Command.sub.arena.function.remove-successfully", "&a成功为竞技场 &e{arena} &a移除附加功能 &b{function}",
            "arena", "function"),
    COMMAND_SUB_ARENA_FUNCTION_RESET_FAIL_NOT_EXISTS("Command.sub.arena.function.reset-fail-not-exists", "&c竞技场 &e{arena} &c本来就未增添ID为 &e'{function_id}' &c的附加功能",
            "arena", "function_id"),
    COMMAND_SUB_ARENA_FUNCTION_RESET_FAIL_NO_DATA_NEEDED("Command.sub.arena.function.reset-fail-no-data-needed", "&c竞技场 &e{arena} &c的附加功能 &e'{function}' &c不需要上传数据",
            "arena", "function"),
    COMMAND_SUB_ARENA_FUNCTION_RESET_ENTER_PROGRESS("Command.sub.arena.function.reset-enter-progress", "&d尝试为竞技场 &a{arena} &d重设附加功能 &b{function}&d 的数据，请按照提示完成操作",
            "arena", "function"),
    COMMAND_SUB_ARENA_FUNCTION_CLEAR_SUCCESSFULLY("Command.sub.arena.function.clear-successfully", "&a成功清除竞技场 &e{arena} &a的所有附加功能",
            "arena"),
    COMMAND_SUB_ARENA_FUNCTION_LIST_EMPTY("Command.sub.arena.function.list-empty", "&c竞技场 &e{arena} &c尚未拥有任何附加功能",
            "arena"),
    COMMAND_SUB_ARENA_FUNCTION_LIST_HEADING("Command.sub.arena.function.list-heading", "&b竞技场 &f{arena} &b的附加功能如下：",
            "arena"),
    COMMAND_SUB_ARENA_FUNCTION_LIST_BODY("Command.sub.arena.function.list-body", new String[]{
            "&f&l{index}. &b{arena_function_name} &3(ID:{arena_function_id})",
            "&7描述：{arena_function_description}",
            "&7数据：{arena_function_data}"},
            "index", "arena_function_name", "arena_function_id", "arena_function_description", "arena_function_data"),
    COMMAND_SUB_ARENA_FUNCTION_LIST_ENDING("Command.sub.arena.function.list-ending", "&b共计 &3&l{number} &b种已添加的附加功能",
            "number"),
    COMMAND_SUB_ARENA_VIEW("Command.sub.arena.view", new String[]{
            "&e==============================",
            "&a名称：&b{arena_name}",
            "&aID：&b{arena_id}",
            "&a类型：&b{arena_type}",
            "&a附加功能：&b{function_number}项[clickable]view_function::&7(点击查看)::&f点击查看已添加的附加功能名称和数据[clickable]",
            "&e==============================",
    },
            new String[][]{
                    {"view_function", "/dueltime arena function list {arena_id}", "", ""}},
            "arena_name", "arena_id", "arena_type", "function_number"),
    COMMAND_SUB_ARENA_DELETE_SUCCESSFULLY("Command.sub.arena.delete-successfully", "&a成功删除ID为 &b{arena_id} &a的竞技场",
            "arena_id"),
    COMMAND_SUB_RANK_ME_DESCRIPTION("Command.sub.rank.me-description", "&b查看自己在各个排行榜的排名"),
    COMMAND_SUB_RANK_VIEW_DESCRIPTION("Command.sub.rank.view-description", "&b查看某个排行榜"),
    COMMAND_SUB_RANK_TYPE_DESCRIPTION("Command.sub.rank.type-description", "&b查看所有类型的排行榜及其对应的ID"),
    COMMAND_SUB_RANK_REFRESH_DESCRIPTION("Command.sub.rank.refresh-description", "&b手动刷新某个排行榜"),
    COMMAND_SUB_RANK_HOLOGRAM_DESCRIPTION("Command.sub.rank.hologram-description", "&b添加/删除/移动某个排行榜对应的全息图"),
    COMMAND_SUB_RANK_ME_HEADING("Command.sub.rank.me-heading", new String[]{
            "&b你在各个排行榜的概括信息如下",
            "&7&m───&f&l&m────────────────────────&7&m───",
            ""
    }),
    COMMAND_SUB_RANK_ME_BODY("Command.sub.rank.me-body", "    &f{ranking_name} &a({rank}&2/{total}&a) [clickable]view_ranking::&7[点击查看]::&f点击查看&f{ranking_name}&f的具体数据[clickable]",
            new String[][]{
                    {"view_ranking", "/dueltime rank view {ranking_id}", "", ""}},
            "ranking_name", "rank", "total", "ranking_id"),
    COMMAND_SUB_RANK_ME_BODY_NO_DATA("Command.sub.rank.me-body-no-data", "    &f{ranking_name} &7(无记录) [clickable]view_ranking::&7[点击查看]::&f点击查看&f{ranking_name}&f的具体数据[clickable]",
            new String[][]{
                    {"view_ranking", "/dueltime rank view {ranking_id}", "", ""}},
            "ranking_name", "ranking_id"),
    COMMAND_SUB_RANK_ME_ENDING("Command.sub.rank.me-ending", new String[]{
            "",
            "&7&m───&f&l&m────────────────────────&7&m───"
    }),
    COMMAND_SUB_RANK_VIEW_HEADING("Command.sub.rank.view-heading", new String[]{
            "{ranking_name}[clickable]ranking_description::&7(查看介绍)::{ranking_description}[clickable]",
            "&7&m──&f&l&m──────────────────&7&m──",
            ""},
            new String[][]{
                    {"ranking_description", "", "", ""}},
            "ranking_name", "ranking_description"),
    COMMAND_SUB_RANK_VIEW_BODY("Command.sub.rank.view-body", "   &f&l[&7{rank}&f&l] &b{player} &f- &3{data}{extra}",
            "rank", "player", "data", "extra"),
    COMMAND_SUB_RANK_VIEW_ENDING("Command.sub.rank.view-ending", new String[]{
            "   [clickable]previous_page::&9[上一页]::点击查看上一页[clickable] &9{current_page}/{total_pages} [clickable]next_page::&9[下一页]::点击查看下一页[clickable]",
            "&7&m──&f&l&m──────────────────&7&m──",
            ""},
            new String[][]{
                    {"previous_page", "/dueltime rank view {ranking_id} {previous_page}", "", ""}, {"next_page", "/dueltime rank view {ranking_id} {next_page}", "", ""}},
            "previous_page", "current_page", "total_pages", "next_page", "ranking_id"),
    COMMAND_SUB_RANK_VIEW_ENDING_SHOW_ME("Command.sub.rank.view-ending-show-me", "&e你在该榜排名&6{rank}/{total} &e数据:&6{data}{extra}",
            "rank", "total", "data", "extra"),
    COMMAND_SUB_RANK_VIEW_ENDING_SHOW_ME_NO_DATA("Command.sub.rank.view-ending-show-me-no-data", "&e你在该排行榜中无数据记录"),
    COMMAND_SUB_RANK_INVALID_RANKING_TYPE_ID("Command.sub.rank.view-invalid-ranking-type-id", "&c类型ID为 &e'{enter}' &c的排行榜不存在 [clickable]view::&f&n点击查看所有类型ID[clickable]",
            new String[][]{
                    {"view", "/dueltime rank type", "", ""}},
            "enter"),
    COMMAND_SUB_RANK_VIEW_EMPTY("Command.sub.rank.view-empty", "&c排行榜 &e{ranking}&c 暂时没有数据",
            "ranking"),
    COMMAND_SUB_RANK_VIEW_INVALID_RANKING_PAGE("Command.sub.rank.view-invalid-ranking-page", "&c请输入有效的页码，该排行榜的总页数为&6{total_pages}&c页",
            "total_pages"),
    COMMAND_SUB_RANK_TYPE_HEADING("Command.sub.rank.type-heading", "&b排行榜类型如下："),
    COMMAND_SUB_RANK_TYPE_BODY("Command.sub.rank.type-body", new String[]{
            "&f&l{index}. &b{type_name} &3(ID:{type_id})",
            "&7描述:&f{description}"},
            "index", "type_name", "type_id", "description"),
    COMMAND_SUB_RANK_TYPE_ENDING("Command.sub.rank.type-ending", "&b共计 &3&l{number} &b种排行榜",
            "number"),
    COMMAND_SUB_RANK_REFRESH_INTERNAL_SUCCESSFULLY("Command.sub.rank.refresh-internal-successfully", "&a成功手动刷新插件内置排行榜：&f{ranking_name}&7(ID:{ranking_id})",
            "ranking_name", "ranking_id"),
    COMMAND_SUB_RANK_HOLOGRAM_DISABLED("Command.sub.rank.hologram-disabled", "&c全息模块已关闭或未装载受本插件支持的全息插件，暂时无法使用此功能"),
    COMMAND_SUB_RANK_HOLOGRAM_ADD_FAIL_ALREADY_EXISTS("Command.sub.rank.hologram-add-fail-already-exists", "&e{ranking} &c已经被添加了全息图，位置：&e{location}",
            "ranking", "location"),
    COMMAND_SUB_RANK_HOLOGRAM_ADD_SUCCESSFULLY("Command.sub.rank.hologram-add-successfully", "&a成功为排行榜 &b{ranking} &a添加全息图，位置：&e{location}",
            "ranking", "location"),
    COMMAND_SUB_RANK_HOLOGRAM_DELETE_FAIL_NOT_EXISTS("Command.sub.rank.hologram-delete-fail-not-exists", "&c无效删除，&e{ranking} &c尚未被添加全息图",
            "ranking"),
    COMMAND_SUB_RANK_HOLOGRAM_DELETE_SUCCESSFULLY("Command.sub.rank.hologram-delete-successfully", "&a成功为排行榜 &b{ranking} &a删除全息图，位置：&e{location}",
            "ranking", "location"),
    COMMAND_SUB_RANK_HOLOGRAM_MOVE_FAIL_NOT_EXISTS("Command.sub.rank.hologram-move-fail-not-exists", "&c无效移动，&e{ranking} &c尚未被添加全息图",
            "ranking"),
    COMMAND_SUB_RANK_HOLOGRAM_MOVE_SUCCESSFULLY("Command.sub.rank.hologram-move-successfully", "&a成功为排行榜 &b{ranking} &a移动全息图，新的位置：&e{location}",
            "ranking", "location"),
    COMMAND_SUB_QUIT_NOT_IN_ARENA("Command.sub.quit.not-in-arena", "&c只有在竞技场比赛时才能使用这个指令"),
    COMMAND_SUB_SPECTATE_FAIL_ARENA_NOT_EXISTS("Command.sub.spectate.fail-arena-not-exists", "&c竞技场 &e'{arena}' &c不存在，无法观看",
            "arena"),
    COMMAND_SUB_SPECTATE_FAIL_ARENA_DISABLED("Command.sub.spectate.fail-arena-disabled", "&c竞技场 &e{arena} &c处于停用状态，无法观看",
            "arena"),
    COMMAND_SUB_SPECTATE_FAIL_ARENA_NO_GAMES("Command.sub.spectate.fail-arena-no-games", "&c竞技场 &e{arena} &c现在没有正在进行的比赛，无法观看",
            "arena"),
    COMMAND_SUB_QUIT_SUCCESSFULLY("Command.sub.quit.successfully", "&b你退出了竞技场 &e{arena} &b上的比赛",
            "arena"),
    RANKING_HOLOGRAM_HEADING("Ranking.hologram.heading", new String[]{
            "{ranking_name}",
            "{ranking_description}"},
            "ranking_name", "ranking_description"),
    RANKING_HOLOGRAM_BODY("Ranking.hologram.body", "&b&lTOP{rank}.&b{player} &f&l- &3{data}{extra}",
            "rank", "player", "data", "extra"),
    RANKING_HOLOGRAM_ENDING("Ranking.hologram.ending", new String[]{
            "---"},
            "ranking_name", "ranking_description"),
    RANKING_TYPE_CLASSIC_WINS_NAME("Ranking.type.classic-wins.name", "&b经典模式胜场榜"),
    RANKING_TYPE_CLASSIC_WINS_DESCRIPTION("Ranking.type.classic-wins.description", "&7在经典模式中赢下的场次越多排名越高"),
    RANKING_TYPE_CLASSIC_WIN_RATE_NAME("Ranking.type.classic-win-rate.name", "&d经典模式胜率榜"),
    RANKING_TYPE_CLASSIC_WIN_RATE_DESCRIPTION("Ranking.type.classic-win-rate.description", "&7在经典模式中的胜率越高排名越靠前"),
    RANKING_TYPE_EXP_NAME("Ranking.type.exp.name", "&a经验榜"),
    RANKING_TYPE_EXP_DESCRIPTION("Ranking.type.exp.description", "&7经验总额越多排名越靠前"),
    RANKING_TOTAL_GAME_NUMBER_TYPE_NAME("Ranking.type.total-game-number.name", "&e全模式场数榜"),
    RANKING_TOTAL_GAME_NUMBER_TYPE_DESCRIPTION("Ranking.type.total-game-number.description", "&7即参与经典模式及DT任意附属插件的任意模式的次数"),
    RANKING_TOTAL_GAME_TIME_TYPE_NAME("Ranking.type.total-game-time.name", "&6全模式时长榜"),
    RANKING_TOTAL_GAME_TIME_TYPE_DESCRIPTION("Ranking.type.total-game-time.description", "&7即参与经典模式及DT任意附属插件的任意模式的时长，按秒数记"),
    RANKING_CLASSIC_GAME_NUMBER_TYPE_NAME("Ranking.type.classic-game-number.name", "&e经典模式场数榜"),
    RANKING_CLASSIC_GAME_NUMBER_TYPE_DESCRIPTION("Ranking.type.classic-game-number.description", "&7即参与经典模式的次数"),
    RANKING_CLASSIC_GAME_TIME_TYPE_NAME("Ranking.type.classic-game-time.name", "&6经典模式时长榜"),
    RANKING_CLASSIC_GAME_TIME_TYPE_DESCRIPTION("Ranking.type.classic-game-time.description", "&7即参与经典模式的时长，按秒数记"),
    ;


    private final String key;
    private final String[] defaultMessage;
    private final String[] variable;
    private final String[][] clickableSettingsList;

    /**
     * 构造单条提示语
     *
     * @param key            对应的配置文件key名
     * @param defaultMessage 默认单条提示语
     * @param variable       变量（可选）
     */
    Msg(String key, String defaultMessage, String... variable) {
        this.key = key;
        this.defaultMessage = new String[]{defaultMessage};
        this.variable = variable;
        this.clickableSettingsList = null;
    }

    /**
     * 构造单条含有可点击文字的提示语
     *
     * @param clickableSettingsList 可点击文字的内定设置信息，依次为：占位符名、执行的指令、建议的指令、打开的URL
     */
    Msg(String key, String defaultMessage, String[][] clickableSettingsList, String... variable) {
        this.key = key;
        this.defaultMessage = new String[]{defaultMessage};
        this.variable = variable;
        this.clickableSettingsList = clickableSettingsList;
    }

    /**
     * 构造多条提示语
     *
     * @param key             对应的配置文件key名
     * @param defaultMessages 默认多条提示语
     * @param variable        变量（可选）
     */
    Msg(String key, String[] defaultMessages, String... variable) {
        this.key = key;
        this.defaultMessage = defaultMessages;
        this.variable = variable;
        this.clickableSettingsList = null;
    }

    /**
     * 构造多条含有可点击文字的提示语
     *
     * @param clickableSettingsList 可点击文字的内定设置信息，依次为：占位符名、执行的指令、建议的指令、打开的URL
     */
    Msg(String key, String[] defaultMessages, String[][] clickableSettingsList, String... variable) {
        this.key = key;
        this.defaultMessage = defaultMessages;
        this.variable = variable;
        this.clickableSettingsList = clickableSettingsList;
    }

    public String getKey() {
        return key;
    }

    public String getDefaultMessage() {
        return defaultMessage[0];
    }

    public String[] getDefaultMessages() {
        return defaultMessage;
    }

    public String[] getVariable() {
        return variable;
    }

    public String[][] getClickableSettingsList() {
        return clickableSettingsList;
    }
}