name: DuelTime4
version: '${project.version}'
main: cn.valorin.dueltime4.DuelTimePlugin
api-version: '1.21'
softdepend: [PlaceholderAPI, DecentHolograms]
commands:
  dueltime:
    description: DuelTime4 commands
    usage: /<command>
    aliases: [dt]
