name: DuelTime4
version: '${project.version}'
main: cn.valorin.dueltime4.DuelTimePlugin
api-version: '1.21'
softdepend: [PlaceholderAPI, DecentHolograms]
commands:
  dueltime:
    description: DuelTime4 commands
    usage: /<command>
    aliases: [dt]

libraries:
  - com.zaxxer:HikariCP:5.1.0
  - org.xerial:sqlite-jdbc:3.45.3.0
  - com.mysql:mysql-connector-j:8.4.0